-- This file is generated by scripts/gen_project_site.py.
-- Do not edit manually.

import VersoBlog
import ProjectSite.GeneratedPages

open Verso Genre Blog Site Syntax

namespace ProjectSite.RouteTable

def projectSite : Site := site ProjectSite.GeneratedPages.homePage /
  "book/" ProjectSite.GeneratedPages.homePage
  "chapters/chap01/section01/" ProjectSite.GeneratedPages.page_chap01_section01
  "chapters/chap01/section01_part1/" ProjectSite.GeneratedPages.page_chap01_section01_part1
  "chapters/chap01/section01_part2/" ProjectSite.GeneratedPages.page_chap01_section01_part2
  "chapters/chap01/section02/" ProjectSite.GeneratedPages.page_chap01_section02
  "chapters/chap01/section03/" ProjectSite.GeneratedPages.page_chap01_section03
  "chapters/chap01/section04/" ProjectSite.GeneratedPages.page_chap01_section04
  "chapters/chap01/section04_part1/" ProjectSite.GeneratedPages.page_chap01_section04_part1
  "chapters/chap01/section04_part2/" ProjectSite.GeneratedPages.page_chap01_section04_part2
  "chapters/chap01/section05/" ProjectSite.GeneratedPages.page_chap01_section05
  "chapters/chap01/" ProjectSite.GeneratedPages.page_chap01
  "chapters/chap02/section01/" ProjectSite.GeneratedPages.page_chap02_section01
  "chapters/chap02/section02/" ProjectSite.GeneratedPages.page_chap02_section02
  "chapters/chap02/section03/" ProjectSite.GeneratedPages.page_chap02_section03
  "chapters/chap02/section04/" ProjectSite.GeneratedPages.page_chap02_section04
  "chapters/chap02/section05/" ProjectSite.GeneratedPages.page_chap02_section05
  "chapters/chap02/" ProjectSite.GeneratedPages.page_chap02
  "chapters/chap03/section01/" ProjectSite.GeneratedPages.page_chap03_section01
  "chapters/chap03/section02/" ProjectSite.GeneratedPages.page_chap03_section02
  "chapters/chap03/section03/" ProjectSite.GeneratedPages.page_chap03_section03
  "chapters/chap03/section04/" ProjectSite.GeneratedPages.page_chap03_section04
  "chapters/chap03/section05/" ProjectSite.GeneratedPages.page_chap03_section05
  "chapters/chap03/section06/" ProjectSite.GeneratedPages.page_chap03_section06
  "chapters/chap03/section07/" ProjectSite.GeneratedPages.page_chap03_section07
  "chapters/chap03/section07_part1/" ProjectSite.GeneratedPages.page_chap03_section07_part1
  "chapters/chap03/section07_part2/" ProjectSite.GeneratedPages.page_chap03_section07_part2
  "chapters/chap03/section08/" ProjectSite.GeneratedPages.page_chap03_section08
  "chapters/chap03/" ProjectSite.GeneratedPages.page_chap03
  "chapters/chap04/section01/" ProjectSite.GeneratedPages.page_chap04_section01
  "chapters/chap04/section02/" ProjectSite.GeneratedPages.page_chap04_section02
  "chapters/chap04/section02_part1/" ProjectSite.GeneratedPages.page_chap04_section02_part1
  "chapters/chap04/section02_part2/" ProjectSite.GeneratedPages.page_chap04_section02_part2
  "chapters/chap04/section02_part3/" ProjectSite.GeneratedPages.page_chap04_section02_part3
  "chapters/chap04/section02_part4/" ProjectSite.GeneratedPages.page_chap04_section02_part4
  "chapters/chap04/section03/" ProjectSite.GeneratedPages.page_chap04_section03
  "chapters/chap04/section04/" ProjectSite.GeneratedPages.page_chap04_section04
  "chapters/chap04/section05/" ProjectSite.GeneratedPages.page_chap04_section05
  "chapters/chap04/section05_part1/" ProjectSite.GeneratedPages.page_chap04_section05_part1
  "chapters/chap04/section05_part2/" ProjectSite.GeneratedPages.page_chap04_section05_part2
  "chapters/chap04/section06/" ProjectSite.GeneratedPages.page_chap04_section06
  "chapters/chap04/section07/" ProjectSite.GeneratedPages.page_chap04_section07
  "chapters/chap04/section07_part1/" ProjectSite.GeneratedPages.page_chap04_section07_part1
  "chapters/chap04/section07_part2/" ProjectSite.GeneratedPages.page_chap04_section07_part2
  "chapters/chap04/section07_part3/" ProjectSite.GeneratedPages.page_chap04_section07_part3
  "chapters/chap04/" ProjectSite.GeneratedPages.page_chap04
  "chapters/chap05/section01/" ProjectSite.GeneratedPages.page_chap05_section01
  "chapters/chap05/section02/" ProjectSite.GeneratedPages.page_chap05_section02
  "chapters/chap05/section02_part1/" ProjectSite.GeneratedPages.page_chap05_section02_part1
  "chapters/chap05/section02_part2/" ProjectSite.GeneratedPages.page_chap05_section02_part2
  "chapters/chap05/section03/" ProjectSite.GeneratedPages.page_chap05_section03
  "chapters/chap05/section04/" ProjectSite.GeneratedPages.page_chap05_section04
  "chapters/chap05/section04_part1/" ProjectSite.GeneratedPages.page_chap05_section04_part1
  "chapters/chap05/section04_part2/" ProjectSite.GeneratedPages.page_chap05_section04_part2
  "chapters/chap05/section05/" ProjectSite.GeneratedPages.page_chap05_section05
  "chapters/chap05/" ProjectSite.GeneratedPages.page_chap05
  "chapters/chap06/section01/" ProjectSite.GeneratedPages.page_chap06_section01
  "chapters/chap06/section02/" ProjectSite.GeneratedPages.page_chap06_section02
  "chapters/chap06/" ProjectSite.GeneratedPages.page_chap06

end ProjectSite.RouteTable
