-- This file is generated by scripts/gen_project_site.py.
-- Do not edit manually.

import SiteSupport.LiterateModule

namespace ProjectSite.GeneratedPages

reasbook_page homePage from Books.IntegerProgramming_Conforti_2014.Book as "IntegerProgramming_Conforti_2014"

end ProjectSite.GeneratedPages
