-- This file is generated by scripts/gen_project_site.py.
-- Do not edit manually.

import VersoBlog
import ProjectSite.GeneratedPages

open Verso Genre Blog Site Syntax

namespace ProjectSite.RouteTable

def projectSite : Site := site ProjectSite.GeneratedPages.homePage /
  "book/" ProjectSite.GeneratedPages.homePage

end ProjectSite.RouteTable
