-- This file is generated by scripts/gen_project_site.py.
-- Do not edit manually.

import SiteSupport.LiterateModule

namespace ProjectSite.GeneratedPages

reasbook_page homePage from Papers.OnSomeLocalRings_Maassaran_2025.Paper as "OnSomeLocalRings_Maassaran_2025"
reasbook_page page_section01 from Papers.OnSomeLocalRings_Maassaran_2025.Sections.section01 as "section01" with ({showInNav := false} : Verso.Genre.Blog.Page.Meta)
reasbook_page page_section01_part1 from Papers.OnSomeLocalRings_Maassaran_2025.Sections.section01_part1 as "section01_part1" with ({showInNav := false} : Verso.Genre.Blog.Page.Meta)
reasbook_page page_section01_part2 from Papers.OnSomeLocalRings_Maassaran_2025.Sections.section01_part2 as "section01_part2" with ({showInNav := false} : Verso.Genre.Blog.Page.Meta)
reasbook_page page_section02 from Papers.OnSomeLocalRings_Maassaran_2025.Sections.section02 as "section02" with ({showInNav := false} : Verso.Genre.Blog.Page.Meta)
reasbook_page page_section02_part1 from Papers.OnSomeLocalRings_Maassaran_2025.Sections.section02_part1 as "section02_part1" with ({showInNav := false} : Verso.Genre.Blog.Page.Meta)
reasbook_page page_section02_part2 from Papers.OnSomeLocalRings_Maassaran_2025.Sections.section02_part2 as "section02_part2" with ({showInNav := false} : Verso.Genre.Blog.Page.Meta)
reasbook_page page_section02_part3 from Papers.OnSomeLocalRings_Maassaran_2025.Sections.section02_part3 as "section02_part3" with ({showInNav := false} : Verso.Genre.Blog.Page.Meta)
reasbook_page page_section02_part4 from Papers.OnSomeLocalRings_Maassaran_2025.Sections.section02_part4 as "section02_part4" with ({showInNav := false} : Verso.Genre.Blog.Page.Meta)

end ProjectSite.GeneratedPages
