-- This file is generated by scripts/gen_project_site.py.
-- Do not edit manually.

import VersoBlog
import ProjectSite.GeneratedPages

open Verso Genre Blog Site Syntax

namespace ProjectSite.RouteTable

def projectSite : Site := site ProjectSite.GeneratedPages.homePage /
  "paper/" ProjectSite.GeneratedPages.homePage
  "sections/section01/" ProjectSite.GeneratedPages.page_section01
  "sections/section01_part1/" ProjectSite.GeneratedPages.page_section01_part1
  "sections/section01_part2/" ProjectSite.GeneratedPages.page_section01_part2
  "sections/section02/" ProjectSite.GeneratedPages.page_section02
  "sections/section02_part1/" ProjectSite.GeneratedPages.page_section02_part1
  "sections/section02_part2/" ProjectSite.GeneratedPages.page_section02_part2
  "sections/section02_part3/" ProjectSite.GeneratedPages.page_section02_part3
  "sections/section02_part4/" ProjectSite.GeneratedPages.page_section02_part4

end ProjectSite.RouteTable
