import Mathlib
import ConvexAnalysis_Rockafellar_1970.Chapters.Chap02.section09_part11

noncomputable section
open scoped Pointwise
open scoped BigOperators
open scoped Topology
open scoped RealInnerProductSpace
open Filter

section Chap02
section Section09
set_option maxHeartbeats 800000 in
/-- Theorem 9.7. Let `f` be a closed proper convex function on `ℝ^n` with `f(0) > 0`,
and let `k` be the positively homogeneous convex function generated by `f`. Then `k` is
proper and `(convexFunctionClosure k)(x)` is the infimum of `(f λ)(x)` over `λ > 0`
together with `λ = 0^+` (encoded here as `f0_plus`), the infimum being attained for each
`x`. If `0 ∈ dom f`, then `k` is closed and the `λ = 0^+` term can be omitted
(but the infimum might not be attained). -/
theorem closure_posHomogeneousGenerated_infimum_rightScalarMultiple {n : Nat}
    {f f0_plus : (Fin n → Real) → EReal}
    (hfclosed : ClosedConvexFunction f)
    (hfproper : ProperConvexFunctionOn (Set.univ : Set (Fin n → Real)) f)
    (hf0 : f (0 : Fin n → Real) > (0 : EReal))
    (hrec :
      Set.recessionCone (epigraph (Set.univ : Set (Fin n → Real)) f) =
        epigraph (Set.univ : Set (Fin n → Real)) f0_plus) :
    let k := positivelyHomogeneousConvexFunctionGenerated f
    (ProperConvexFunctionOn (Set.univ : Set (Fin n → Real)) k) ∧
      (∀ x : Fin n → Real,
        convexFunctionClosure k x =
          sInf
            (Set.insert (f0_plus x)
              { z : EReal | ∃ lam : Real, 0 < lam ∧ z = rightScalarMultiple f lam x })) ∧
      (∀ x : Fin n → Real,
        ∃ z ∈
            Set.insert (f0_plus x)
              { z : EReal | ∃ lam : Real, 0 < lam ∧ z = rightScalarMultiple f lam x },
          convexFunctionClosure k x = z) ∧
      ((0 : Fin n → Real) ∈ effectiveDomain (Set.univ : Set (Fin n → Real)) f →
        ClosedConvexFunction k ∧
          (∀ x : Fin n → Real,
            k x =
              sInf { z : EReal | ∃ lam : Real, 0 < lam ∧ z = rightScalarMultiple f lam x })) := by
  classical
  -- Unfold the `let`-binding to work with `k`.
  dsimp
  set k := positivelyHomogeneousConvexFunctionGenerated f with hk
  have hfconv : ConvexFunctionOn (Set.univ : Set (Fin n → Real)) f := hfproper.1
  have hfinite : ∃ x, f x ≠ (⊤ : EReal) := by
    rcases hfproper.2.1 with ⟨⟨x, μ⟩, hx⟩
    have hle : f x ≤ (μ : EReal) := (mem_epigraph_univ_iff (f := f)).1 hx
    refine ⟨x, ?_⟩
    intro htop
    have hle' : False := by
      refine (not_top_le_coe (r := μ) ?_)
      rw [← htop]
      exact hle
    exact hle'
  have hk_formula :
      ∀ x : Fin n → Real,
        k x = sInf { z : EReal | ∃ lam : Real, 0 ≤ lam ∧ z = rightScalarMultiple f lam x } := by
    rw [hk]
    exact (infimumRepresentation_posHomogeneousHull (h := f) hfconv hfinite).1
  set C : Set (Fin (n + 1) → Real) :=
    (prodLinearEquiv_append_coord (n := n)) '' epigraph (Set.univ : Set (Fin n → Real)) f
  have hCne : Set.Nonempty C := by
    rcases hfproper.2.1 with ⟨p, hp⟩
    exact ⟨(prodLinearEquiv_append_coord (n := n)) p, ⟨p, hp, rfl⟩⟩
  have hCclosed : IsClosed C := by
    have hclosed_sub :
        ∀ α : Real, IsClosed {x : Fin n → Real | f x ≤ (α : EReal)} :=
      (lowerSemicontinuous_iff_closed_sublevel_iff_closed_epigraph (f := f)).1.mp hfclosed.2
    have hclosed_epi :
        IsClosed (epigraph (Set.univ : Set (Fin n → Real)) f) :=
      (lowerSemicontinuous_iff_closed_sublevel_iff_closed_epigraph (f := f)).2.mp hclosed_sub
    let hhome := (prodLinearEquiv_append_coord (n := n)).toAffineEquiv.toHomeomorphOfFiniteDimensional
    have hclosed' :
        IsClosed ((hhome : _ → _) '' epigraph (Set.univ : Set (Fin n → Real)) f) :=
      (hhome.isClosed_image (s := epigraph (Set.univ : Set (Fin n → Real)) f)).2 hclosed_epi
    simpa [C, hhome, AffineEquiv.coe_toHomeomorphOfFiniteDimensional] using hclosed'
  have hCconv : Convex Real C := by
    have hconv_epi :
        Convex Real (epigraph (Set.univ : Set (Fin n → Real)) f) := by
      simpa [ConvexFunction] using
        (convex_epigraph_of_convexFunctionOn (f := f) (hf := hfconv))
    simpa [C] using hconv_epi.linear_image (prodLinearEquiv_append_coord (n := n)).toLinearMap
  have hC0 : (0 : Fin (n + 1) → Real) ∉ C := by
    intro h0
    rcases h0 with ⟨p, hp, hp0⟩
    have hp0' : p = 0 := by
      apply (prodLinearEquiv_append_coord (n := n)).injective
      simpa using hp0
    subst hp0'
    have hle : f (0 : Fin n → Real) ≤ (0 : EReal) := by
      simpa using (mem_epigraph_univ_iff (f := f)).1 hp
    exact (not_lt_of_ge hle) hf0
  have hclosure_union :
      closure (convexConeGenerated (n + 1) C) =
        (⋃ (lam : Real) (_ : 0 < lam),
          (prodLinearEquiv_append_coord (n := n)) ''
            epigraph (Set.univ : Set (Fin n → Real)) (rightScalarMultiple f lam)) ∪
        (prodLinearEquiv_append_coord (n := n)) '' epigraph (Set.univ : Set (Fin n → Real)) f0_plus := by
    simpa [C] using
      (closure_convexConeGenerated_embedded_epigraph_eq_union
        (n := n) (f := f) (f0_plus := f0_plus) hfconv hrec hCne hCclosed hCconv hC0)
  have hcone_img :
      (prodLinearEquiv_append_coord (n := n)) '' convexConeGeneratedEpigraph f =
        convexConeGenerated (n + 1) C := by
    simpa [C] using
      (convexConeGenerated_embedded_epigraph_eq_image_convexConeGeneratedEpigraph
        (n := n) (f := f) hfconv)
  have hclosure_union' :
      closure ((prodLinearEquiv_append_coord (n := n)) '' convexConeGeneratedEpigraph f) =
        (⋃ (lam : Real) (_ : 0 < lam),
          (prodLinearEquiv_append_coord (n := n)) ''
            epigraph (Set.univ : Set (Fin n → Real)) (rightScalarMultiple f lam)) ∪
        (prodLinearEquiv_append_coord (n := n)) '' epigraph (Set.univ : Set (Fin n → Real)) f0_plus := by
    calc
      closure ((prodLinearEquiv_append_coord (n := n)) '' convexConeGeneratedEpigraph f) =
          closure (convexConeGenerated (n + 1) C) := by
        simp [hcone_img]
      _ = _ := hclosure_union
  -- The generated cone sits inside the epigraph of `k`.
  have hcone_subset :
      convexConeGeneratedEpigraph f ⊆
        epigraph (Set.univ : Set (Fin n → Real)) k := by
    rw [hk]
    exact (convexConeGeneratedEpigraph_subset_epigraph_posHom (f := f))
  have hclosure_cone_subset :
      closure ((prodLinearEquiv_append_coord (n := n)) '' convexConeGeneratedEpigraph f) ⊆
        closure ((prodLinearEquiv_append_coord (n := n)) ''
          epigraph (Set.univ : Set (Fin n → Real)) k) := by
    have hsubset :
        (prodLinearEquiv_append_coord (n := n)) '' convexConeGeneratedEpigraph f ⊆
          (prodLinearEquiv_append_coord (n := n)) ''
            epigraph (Set.univ : Set (Fin n → Real)) k := by
      intro y hy
      rcases hy with ⟨p, hp, rfl⟩
      exact ⟨p, hcone_subset hp, rfl⟩
    exact closure_mono hsubset
  have hclosure_union'' :
      closure (convexConeGeneratedEpigraph f) =
        (⋃ (lam : Real) (_ : 0 < lam),
          epigraph (Set.univ : Set (Fin n → Real)) (rightScalarMultiple f lam)) ∪
        epigraph (Set.univ : Set (Fin n → Real)) f0_plus := by
    exact
      closure_convexConeGeneratedEpigraph_eq_union
        (n := n) (f := f) (f0_plus := f0_plus) hclosure_union'
  have hk_conv_ne :
      ConvexFunctionOn (Set.univ : Set (Fin n → Real)) k ∧
        Set.Nonempty (epigraph (Set.univ : Set (Fin n → Real)) k) := by
    rw [hk]
    exact (posHomGenerated_convex_and_nonempty (n := n) (f := f) hfconv)
  have hk_conv : ConvexFunctionOn (Set.univ : Set (Fin n → Real)) k := hk_conv_ne.1
  have hk_ne_epi : Set.Nonempty (epigraph (Set.univ : Set (Fin n → Real)) k) := hk_conv_ne.2
  -- The epigraph of `k` sits in the closed cone generated by the epigraph of `f`.
  have h_epi_subset :
      epigraph (Set.univ : Set (Fin n → Real)) k ⊆
        closure (convexConeGeneratedEpigraph f) := by
    intro p hp
    rcases p with ⟨x, μ⟩
    have hle : k x ≤ (μ : EReal) := (mem_epigraph_univ_iff (f := k)).1 hp
    -- First handle the strict inequality case via the `sInf` formula.
    by_cases hlt : k x < (μ : EReal)
    · set S0 : Set EReal :=
        { z : EReal | ∃ lam : Real, 0 ≤ lam ∧ z = rightScalarMultiple f lam x }
      have hlt' : sInf S0 < (μ : EReal) := by
        simpa [hk_formula x, S0] using hlt
      rcases (sInf_lt_iff).1 hlt' with ⟨z, hzS0, hzlt⟩
      rcases hzS0 with ⟨lam, hlam, rfl⟩
      have hmem_union :
          (x, μ) ∈
              (⋃ (t : Real) (_ : 0 < t),
                epigraph (Set.univ : Set (Fin n → Real)) (rightScalarMultiple f t)) ∪
                epigraph (Set.univ : Set (Fin n → Real)) f0_plus := by
        by_cases hpos : 0 < lam
        · have hle' : rightScalarMultiple f lam x ≤ (μ : EReal) :=
            le_of_lt hzlt
          have hmem :
              (x, μ) ∈ epigraph (Set.univ : Set (Fin n → Real))
                (rightScalarMultiple f lam) :=
            (mem_epigraph_univ_iff (f := rightScalarMultiple f lam)).2 hle'
          refine Or.inl ?_
          refine Set.mem_iUnion.2 ⟨lam, ?_⟩
          refine Set.mem_iUnion.2 ⟨hpos, ?_⟩
          exact hmem
        · have hlam0 : lam = 0 := le_antisymm (le_of_not_gt hpos) hlam
          subst hlam0
          have hne_epi :
              Set.Nonempty (epigraph (Set.univ : Set (Fin n → Real)) f) := hfproper.2.1
          have hval :=
            rightScalarMultiple_zero_eval (f := f) hne_epi x
          by_cases hx0 : x = 0
          · subst hx0
            have hμpos : (0 : EReal) < (μ : EReal) := by
              simpa [hval] using hzlt
            have hzero :
                ((0 : Fin n → Real), (0 : Real)) ∈
                  epigraph (Set.univ : Set (Fin n → Real)) f0_plus := by
              have h0mem :
                  (0 : (Fin n → Real) × Real) ∈
                    Set.recessionCone
                      (epigraph (Set.univ : Set (Fin n → Real)) f) := by
                intro y hy t ht
                simpa using hy
              simpa [hrec] using h0mem
            have hle0 :
                f0_plus (0 : Fin n → Real) ≤ (0 : EReal) :=
              (mem_epigraph_univ_iff (f := f0_plus)).1 hzero
            have hleμ : f0_plus (0 : Fin n → Real) ≤ (μ : EReal) :=
              le_trans hle0 (le_of_lt hμpos)
            have hmem :
                ((0 : Fin n → Real), μ) ∈
                  epigraph (Set.univ : Set (Fin n → Real)) f0_plus :=
              (mem_epigraph_univ_iff (f := f0_plus)).2 hleμ
            exact Or.inr hmem
          · have htop := hval
            simp [hx0] at htop
            have hnot : ¬ rightScalarMultiple f 0 x < (μ : EReal) := by
              simp [htop]
            exact (hnot hzlt).elim
      have hmem_closure :
          (x, μ) ∈ closure (convexConeGeneratedEpigraph f) := by
        rw [hclosure_union'']
        exact hmem_union
      exact hmem_closure
    · -- Equality case: approximate by a decreasing sequence from above.
      have hEq : k x = (μ : EReal) := by
        exact le_antisymm hle (not_lt.mp hlt)
      have hclosed : IsClosed (closure (convexConeGeneratedEpigraph f)) := isClosed_closure
      have hmem_seq :
          ∀ m : ℕ,
            (x, μ + (1 : Real) / (m + 1)) ∈ closure (convexConeGeneratedEpigraph f) := by
        intro m
        have hlt' :
            k x < ((μ + (1 : Real) / (m + 1) : Real) : EReal) := by
          have hpos :
              (0 : Real) < (1 : Real) / (m + 1) := by
            have : 0 < (m + 1 : Real) := by
              exact_mod_cast (Nat.succ_pos m)
            exact one_div_pos.mpr this
          have hpos' : (μ : EReal) < ((μ + (1 : Real) / (m + 1) : Real) : EReal) := by
            have hpos'' : (μ : Real) < μ + (1 : Real) / (m + 1) := by linarith
            exact (EReal.coe_lt_coe_iff).2 hpos''
          simpa [hEq] using hpos'
        have hmem' : (x, μ + (1 : Real) / (m + 1)) ∈
            closure (convexConeGeneratedEpigraph f) := by
          -- apply the strict case to `μ + 1/(n+1)`
          have hle' :
              k x ≤ ((μ + (1 : Real) / (m + 1) : Real) : EReal) :=
            le_of_lt hlt'
          have hmem_epi :
              (x, μ + (1 : Real) / (m + 1)) ∈
                epigraph (Set.univ : Set (Fin n → Real)) k :=
            (mem_epigraph_univ_iff (f := k)).2 hle'
          -- reuse the strict-case proof by calling it directly
          have hmem'' :
              (x, μ + (1 : Real) / (m + 1)) ∈
                closure (convexConeGeneratedEpigraph f) := by
              -- re-run the strict case using the same argument as above
              -- with `μ + 1/(n+1)` in place of `μ`.
              have : k x < ((μ + (1 : Real) / (m + 1) : Real) : EReal) := hlt'
              -- short-circuit by reusing the earlier branch
              -- (the proof above is not packaged as a lemma, so we redo a small part)
              set S0 : Set EReal :=
                { z : EReal | ∃ lam : Real, 0 ≤ lam ∧ z = rightScalarMultiple f lam x }
              have hlt'' : sInf S0 < ((μ + (1 : Real) / (m + 1) : Real) : EReal) := by
                simpa [hk_formula x, S0] using hlt'
              rcases (sInf_lt_iff).1 hlt'' with ⟨z, hzS0, hzlt⟩
              rcases hzS0 with ⟨lam, hlam, rfl⟩
              have hmem_union :
                  (x, μ + (1 : Real) / (m + 1)) ∈
                      (⋃ (t : Real) (_ : 0 < t),
                        epigraph (Set.univ : Set (Fin n → Real)) (rightScalarMultiple f t)) ∪
                        epigraph (Set.univ : Set (Fin n → Real)) f0_plus := by
                by_cases hpos : 0 < lam
                · have hle' :
                    rightScalarMultiple f lam x ≤
                      ((μ + (1 : Real) / (m + 1) : Real) : EReal) :=
                    le_of_lt hzlt
                  have hmem :
                      (x, μ + (1 : Real) / (m + 1)) ∈
                        epigraph (Set.univ : Set (Fin n → Real))
                          (rightScalarMultiple f lam) :=
                    (mem_epigraph_univ_iff (f := rightScalarMultiple f lam)).2 hle'
                  refine Or.inl ?_
                  refine Set.mem_iUnion.2 ⟨lam, ?_⟩
                  refine Set.mem_iUnion.2 ⟨hpos, ?_⟩
                  exact hmem
                · have hlam0 : lam = 0 := le_antisymm (le_of_not_gt hpos) hlam
                  subst hlam0
                  have hne_epi :
                      Set.Nonempty (epigraph (Set.univ : Set (Fin n → Real)) f) := hfproper.2.1
                  have hval :=
                    rightScalarMultiple_zero_eval (f := f) hne_epi x
                  by_cases hx0 : x = 0
                  · subst hx0
                    have hμpos :
                        (0 : EReal) <
                          ((μ + (1 : Real) / (m + 1) : Real) : EReal) := by
                      simpa [hval] using hzlt
                    have hzero :
                        ((0 : Fin n → Real), (0 : Real)) ∈
                          epigraph (Set.univ : Set (Fin n → Real)) f0_plus := by
                      have h0mem :
                          (0 : (Fin n → Real) × Real) ∈
                            Set.recessionCone
                              (epigraph (Set.univ : Set (Fin n → Real)) f) := by
                        intro y hy t ht
                        simpa using hy
                      simpa [hrec] using h0mem
                    have hle0 :
                        f0_plus (0 : Fin n → Real) ≤ (0 : EReal) :=
                      (mem_epigraph_univ_iff (f := f0_plus)).1 hzero
                    have hleμ :
                        f0_plus (0 : Fin n → Real) ≤
                          ((μ + (1 : Real) / (m + 1) : Real) : EReal) :=
                      le_trans hle0 (le_of_lt hμpos)
                    have hmem :
                        ((0 : Fin n → Real), μ + (1 : Real) / (m + 1)) ∈
                          epigraph (Set.univ : Set (Fin n → Real)) f0_plus :=
                      (mem_epigraph_univ_iff (f := f0_plus)).2 hleμ
                    exact Or.inr hmem
                  · have htop := hval
                    simp [hx0] at htop
                    have : ¬ (rightScalarMultiple f 0 x) <
                        ((μ + (1 : Real) / (m + 1) : Real) : EReal) := by
                      simp [htop]
                    exact (this hzlt).elim
              simpa [hclosure_union''] using hmem_union
          exact hmem''
        exact hmem'
      have hlim :
          Filter.Tendsto
            (fun n : ℕ => (x, μ + (1 : Real) / (n + 1))) Filter.atTop (𝓝 (x, μ)) := by
        have h1 :
            Filter.Tendsto (fun _ : ℕ => x) Filter.atTop (𝓝 x) :=
          tendsto_const_nhds
        have h2' :
            Filter.Tendsto (fun n : ℕ => (1 : Real) / (n + 1)) Filter.atTop
              (𝓝 (0 : Real)) :=
          tendsto_one_div_add_atTop_nhds_zero_nat
        have h2 :
            Filter.Tendsto
              (fun n : ℕ => μ + (1 : Real) / (n + 1)) Filter.atTop (𝓝 μ) := by
          simpa using (tendsto_const_nhds.add h2')
        exact Filter.Tendsto.prodMk_nhds h1 h2
      exact hclosed.mem_of_tendsto hlim (eventually_of_forall hmem_seq)
  have hkproper : ProperConvexFunctionOn (Set.univ : Set (Fin n → Real)) k := by
    refine ⟨hk_conv, hk_ne_epi, ?_⟩
    intro x hx hbot
    -- Use the closed cone description to rule out `k x = ⊥`.
    have hxbot : k x = (⊥ : EReal) := hbot
    have hmem_epi : (x, (-1 : Real)) ∈ epigraph (Set.univ : Set (Fin n → Real)) k := by
      have hle : k x ≤ ((-1 : Real) : EReal) := by
        simp [hxbot]
      exact (mem_epigraph_univ_iff (f := k)).2 hle
    have hmem_closure : (x, (-1 : Real)) ∈ closure (convexConeGeneratedEpigraph f) :=
      h_epi_subset hmem_epi
    -- Scaling the vertical line gives a negative vertical at the origin.
    have hmem_union :
        (x, (-1 : Real)) ∈
            (⋃ (t : Real) (_ : 0 < t),
              epigraph (Set.univ : Set (Fin n → Real)) (rightScalarMultiple f t)) ∪
            epigraph (Set.univ : Set (Fin n → Real)) f0_plus := by
      rw [hclosure_union''] at hmem_closure
      exact hmem_closure
    have hclosed_union :
        IsClosed
          ((⋃ (t : Real) (_ : 0 < t),
            epigraph (Set.univ : Set (Fin n → Real)) (rightScalarMultiple f t)) ∪
            epigraph (Set.univ : Set (Fin n → Real)) f0_plus) := by
      simpa [hclosure_union''] using
        (isClosed_closure (s := convexConeGeneratedEpigraph f))
    -- For any `t > 0`, the point `(t • x, -1)` lies in the union.
    have hmem_scaled :
        ∀ t : Real, 0 < t →
          (t • x, (-1 : Real)) ∈
            (⋃ (s : Real) (_ : 0 < s),
              epigraph (Set.univ : Set (Fin n → Real)) (rightScalarMultiple f s)) ∪
            epigraph (Set.univ : Set (Fin n → Real)) f0_plus := by
      intro t ht
      -- the union is a cone, so scale `(x, -1/t)`
      have hmem_vert :
          (x, (-1 : Real) / t) ∈
            (⋃ (s : Real) (_ : 0 < s),
              epigraph (Set.univ : Set (Fin n → Real)) (rightScalarMultiple f s)) ∪
            epigraph (Set.univ : Set (Fin n → Real)) f0_plus := by
        have hle : k x ≤ ((-1 : Real) / t : EReal) := by
          have hbot' : k x = (⊥ : EReal) := hxbot
          simp [hbot']
        have hmem_epi :
            (x, (-1 : Real) / t) ∈ epigraph (Set.univ : Set (Fin n → Real)) k :=
          (mem_epigraph_univ_iff (f := k)).2 hle
        have hmem_closure' := h_epi_subset hmem_epi
        rw [hclosure_union''] at hmem_closure'
        exact hmem_closure'
      -- scale within the union
      rcases hmem_vert with hmem_vert | hmem_vert
      · rcases (Set.mem_iUnion).1 hmem_vert with ⟨s, hmem_vert⟩
        rcases (Set.mem_iUnion).1 hmem_vert with ⟨hspos, hmem_vert⟩
        have hle' :
            rightScalarMultiple f s x ≤ ((-1 : Real) / t : EReal) :=
          (mem_epigraph_univ_iff (f := rightScalarMultiple f s)).1 hmem_vert
        have hle'' :
            rightScalarMultiple f (t * s) (t • x) ≤ ((-1 : Real) : EReal) := by
          -- scale the inequality
          have hmul :=
            ereal_mul_le_mul_of_pos_left_general (t := t) (ht := ht) hle'
          have hright :
              ((t : Real) : EReal) * ((-1 : Real) / t : EReal) = (-1 : EReal) := by
            have hdiv : ((-1 : Real) / t : EReal) = (t⁻¹ : EReal) * (-1 : EReal) := by
              simp [div_eq_mul_inv, mul_comm]
            calc
              (t : EReal) * ((-1 : Real) / t : EReal) =
                  (t : EReal) * ((t⁻¹ : EReal) * (-1 : EReal)) := by
                    rw [hdiv]
              _ = (-1 : EReal) := by
                    simpa using
                      (ereal_mul_inv_smul (t := t) (ht := ht) (x := (-1 : EReal)))
          have hmul' :
              ((t : Real) : EReal) * rightScalarMultiple f s x ≤ ((-1 : Real) : EReal) := by
            calc
              ((t : Real) : EReal) * rightScalarMultiple f s x ≤
                  ((t : Real) : EReal) * ((-1 : Real) / t : EReal) := hmul
              _ = (-1 : EReal) := hright
          have hspos' : 0 < t * s := mul_pos ht hspos
          have hpos_ts :=
            rightScalarMultiple_pos (f := f) (lam := t * s) hfconv hspos' (t • x)
          have hpos_s :=
            rightScalarMultiple_pos (f := f) (lam := s) hfconv hspos x
          have hsmul : (t * s)⁻¹ • (t • x) = s⁻¹ • x := by
            have ht0 : t ≠ 0 := ne_of_gt ht
            have hs0 : s ≠ 0 := ne_of_gt hspos
            have hscale : (t * s)⁻¹ * t = s⁻¹ := by
              field_simp [ht0, hs0]
            calc
              (t * s)⁻¹ • (t • x) = ((t * s)⁻¹ * t) • x := by
                rw [smul_smul]
              _ = s⁻¹ • x := by
                rw [hscale]
          have hsmul' : (s⁻¹ * t⁻¹) • t • x = s⁻¹ • x := by
            have ht0 : t ≠ 0 := ne_of_gt ht
            calc
              (s⁻¹ * t⁻¹) • t • x = ((s⁻¹ * t⁻¹) * t) • x := by
                rw [smul_smul]
              _ = s⁻¹ • x := by
                simp [ht0]
          have hmul1 :
              ((t * s : Real) : EReal) * f (s⁻¹ • x) ≤ ((-1 : Real) : EReal) := by
            have hmul1' :
                ((t : EReal) * ((s : EReal) * f (s⁻¹ • x))) ≤ ((-1 : Real) : EReal) := by
              simpa [hpos_s, mul_assoc] using hmul'
            simpa [mul_comm, mul_left_comm, mul_assoc, EReal.coe_mul] using hmul1'
          have hmul2 :
              ((t * s : Real) : EReal) * f ((t * s)⁻¹ • (t • x)) ≤ ((-1 : Real) : EReal) := by
            simpa [hsmul'] using hmul1
          rw [hpos_ts]
          exact hmul2
        have hmem' :
            (t • x, (-1 : Real)) ∈
              epigraph (Set.univ : Set (Fin n → Real))
                (rightScalarMultiple f (t * s)) :=
          (mem_epigraph_univ_iff (f := rightScalarMultiple f (t * s))).2 hle''
        refine Or.inl ?_
        refine Set.mem_iUnion.2 ⟨t * s, ?_⟩
        refine Set.mem_iUnion.2 ⟨mul_pos ht hspos, ?_⟩
        exact hmem'
      · -- scaling a recession direction stays in the recession cone
        have hmem' :
            (t • x, (-1 : Real)) ∈
              epigraph (Set.univ : Set (Fin n → Real)) f0_plus := by
          have hle' : f0_plus x ≤ ((-1 : Real) / t : EReal) :=
            (mem_epigraph_univ_iff (f := f0_plus)).1 hmem_vert
          have hle'' :=
            ereal_mul_le_mul_of_pos_left_general (t := t) (ht := ht) hle'
          have hne : (t : Real) ≠ 0 := ne_of_gt ht
          have hle''' : f0_plus (t • x) ≤ ((-1 : Real) : EReal) := by
            -- use that epigraph of `f0_plus` is a cone
            have hrec' :
                (x, (-1 : Real) / t) ∈
                  Set.recessionCone
                    (epigraph (Set.univ : Set (Fin n → Real)) f) := by
              simpa [hrec] using hmem_vert
            have hrec'' :
                (t • x, (-1 : Real)) ∈
                  Set.recessionCone
                    (epigraph (Set.univ : Set (Fin n → Real)) f) := by
              intro y hy s hs
              have hrec_mem := hrec' (x := y) hy (t := s * t) (by nlinarith)
              have ht0 : t ≠ 0 := ne_of_gt ht
              have hmul : s * (t * (-1 / t)) = -s := by
                field_simp [ht0, mul_comm, mul_left_comm, mul_assoc]
              simpa [smul_smul, mul_assoc, hmul] using hrec_mem
            have hmem' :
                (t • x, (-1 : Real)) ∈
                  epigraph (Set.univ : Set (Fin n → Real)) f0_plus := by
              simpa [hrec] using hrec''
            exact (mem_epigraph_univ_iff (f := f0_plus)).1 hmem'
          exact (mem_epigraph_univ_iff (f := f0_plus)).2 hle'''
        exact Or.inr hmem'
    have hmem_limit :
        ((0 : Fin n → Real), (-1 : Real)) ∈
          (⋃ (t : Real) (_ : 0 < t),
            epigraph (Set.univ : Set (Fin n → Real)) (rightScalarMultiple f t)) ∪
          epigraph (Set.univ : Set (Fin n → Real)) f0_plus := by
      have hmem_seq :
          ∀ m : ℕ,
            (((1 : Real) / (m + 1)) • x, (-1 : Real)) ∈
              (⋃ (t : Real) (_ : 0 < t),
                epigraph (Set.univ : Set (Fin n → Real)) (rightScalarMultiple f t)) ∪
              epigraph (Set.univ : Set (Fin n → Real)) f0_plus := by
        intro m
        have hpos : 0 < (1 : Real) / (m + 1) := by
          have : 0 < (m + 1 : Real) := by
            exact_mod_cast (Nat.succ_pos m)
          exact one_div_pos.mpr this
        simpa using (hmem_scaled ((1 : Real) / (m + 1)) hpos)
      have hlim :
          Filter.Tendsto
            (fun n : ℕ => (((1 : Real) / (n + 1)) • x, (-1 : Real))) Filter.atTop
              (𝓝 ((0 : Fin n → Real), (-1 : Real))) := by
        have h1 :
            Filter.Tendsto
              (fun n : ℕ => (1 : Real) / (n + 1)) Filter.atTop (𝓝 (0 : Real)) :=
          tendsto_one_div_add_atTop_nhds_zero_nat
        have h1' :
            Filter.Tendsto (fun n : ℕ => ((1 : Real) / (n + 1)) • x) Filter.atTop
              (𝓝 (0 : Fin n → Real)) := by
          have h1' :=
            h1.smul
              (tendsto_const_nhds :
                Filter.Tendsto (fun _ : ℕ => x) Filter.atTop (𝓝 x))
          have hzero : (0 : Real) • x = (0 : Fin n → Real) := by
            simp
          simpa [hzero] using h1'
        have h2 : Filter.Tendsto (fun _ : ℕ => (-1 : Real)) Filter.atTop (𝓝 (-1 : Real)) :=
          tendsto_const_nhds
        exact Filter.Tendsto.prodMk_nhds h1' h2
      exact hclosed_union.mem_of_tendsto hlim (eventually_of_forall hmem_seq)
    -- show that the union cannot contain negative verticals
    have hneg_not :
        ((0 : Fin n → Real), (-1 : Real)) ∉
          (⋃ (t : Real) (_ : 0 < t),
            epigraph (Set.univ : Set (Fin n → Real)) (rightScalarMultiple f t)) ∪
          epigraph (Set.univ : Set (Fin n → Real)) f0_plus := by
      intro hmem
      rcases hmem with hmem | hmem
      · rcases (Set.mem_iUnion).1 hmem with ⟨t, hmem⟩
        rcases (Set.mem_iUnion).1 hmem with ⟨ht, hmem⟩
        have hle :
            rightScalarMultiple f t (0 : Fin n → Real) ≤ ((-1 : Real) : EReal) :=
          (mem_epigraph_univ_iff (f := rightScalarMultiple f t)).1 hmem
        have hpos0 : (0 : EReal) < rightScalarMultiple f t (0 : Fin n → Real) := by
          have hpos' : (0 : EReal) < (t : EReal) := by
            simpa using (EReal.coe_lt_coe_iff).2 ht
          have hpos0' : (0 : EReal) < f (0 : Fin n → Real) := hf0
          have hright :=
            rightScalarMultiple_pos (f := f) (lam := t) hfconv ht (0 : Fin n → Real)
          have hmul : (0 : EReal) < (t : EReal) * f (0 : Fin n → Real) :=
            EReal.mul_pos hpos' hpos0'
          simp [hright, hmul]
        have hnot : ¬ (rightScalarMultiple f t (0 : Fin n → Real) ≤ ((-1 : Real) : EReal)) := by
          have hlt : ((-1 : Real) : EReal) < rightScalarMultiple f t (0 : Fin n → Real) :=
            lt_trans (by simp) hpos0
          exact not_le_of_gt hlt
        exact hnot hle
      · have hmem' :
            (0, (-1 : Real)) ∈
              Set.recessionCone
                (epigraph (Set.univ : Set (Fin n → Real)) f) := by
          simpa [hrec] using hmem
        exact (no_neg_vertical_recession_epigraph (f := f) hfproper (μ := (-1 : Real)) (by norm_num))
          hmem'
    exact (hneg_not hmem_limit).elim
  refine And.intro hkproper ?_
  ·
    have hcl_formula :
        ∀ x : Fin n → Real,
          convexFunctionClosure k x =
            sInf
              (Set.insert (f0_plus x)
                { z : EReal | ∃ lam : Real, 0 < lam ∧
                    z = rightScalarMultiple f lam x }) := by
      intro x
      -- TODO: identify attaching closure with `convexFunctionClosure k`.
      -- identify the closed cone with the epigraph of `convexFunctionClosure k`
      have hnotbot : ∀ x : Fin n → Real, k x ≠ (⊥ : EReal) := by
        intro x
        by_contra hbot
        have hproper : False := by
          have hx := hbot
          -- reuse the previous argument
          have hbot' : k x = (⊥ : EReal) := hbot
          have hmem_epi : (x, (-1 : Real)) ∈ epigraph (Set.univ : Set (Fin n → Real)) k := by
            have hle : k x ≤ ((-1 : Real) : EReal) := by
              simp [hbot']
            exact (mem_epigraph_univ_iff (f := k)).2 hle
          have hmem_closure : (x, (-1 : Real)) ∈ closure (convexConeGeneratedEpigraph f) :=
            h_epi_subset hmem_epi
          have hmem_union :
              (x, (-1 : Real)) ∈
                  (⋃ (t : Real) (_ : 0 < t),
                    epigraph (Set.univ : Set (Fin n → Real)) (rightScalarMultiple f t)) ∪
                  epigraph (Set.univ : Set (Fin n → Real)) f0_plus := by
            simpa [hclosure_union''] using hmem_closure
          -- the union has no negative verticals at the origin
          have hclosed_union :
              IsClosed
                ((⋃ (t : Real) (_ : 0 < t),
                  epigraph (Set.univ : Set (Fin n → Real)) (rightScalarMultiple f t)) ∪
                  epigraph (Set.univ : Set (Fin n → Real)) f0_plus) := by
            simpa [hclosure_union''] using
              (isClosed_closure (s := convexConeGeneratedEpigraph f))
          have hmem_scaled :
              ∀ t : Real, 0 < t →
                (t • x, (-1 : Real)) ∈
                  (⋃ (s : Real) (_ : 0 < s),
                    epigraph (Set.univ : Set (Fin n → Real)) (rightScalarMultiple f s)) ∪
                  epigraph (Set.univ : Set (Fin n → Real)) f0_plus := by
            intro t ht
            have hmem_vert :
                (x, (-1 : Real) / t) ∈
                  (⋃ (s : Real) (_ : 0 < s),
                    epigraph (Set.univ : Set (Fin n → Real)) (rightScalarMultiple f s)) ∪
                  epigraph (Set.univ : Set (Fin n → Real)) f0_plus := by
              have hle : k x ≤ ((-1 : Real) / t : EReal) := by
                simp [hbot']
              have hmem_epi :
                  (x, (-1 : Real) / t) ∈ epigraph (Set.univ : Set (Fin n → Real)) k :=
                (mem_epigraph_univ_iff (f := k)).2 hle
              have hmem_closure' := h_epi_subset hmem_epi
              simpa [hclosure_union''] using hmem_closure'
            rcases hmem_vert with hmem_vert | hmem_vert
            · rcases (Set.mem_iUnion).1 hmem_vert with ⟨s, hmem_vert⟩
              rcases (Set.mem_iUnion).1 hmem_vert with ⟨hspos, hmem_vert⟩
              have hle' :
                  rightScalarMultiple f s x ≤ ((-1 : Real) / t : EReal) :=
                (mem_epigraph_univ_iff (f := rightScalarMultiple f s)).1 hmem_vert
              have hle'' :
                  rightScalarMultiple f (t * s) (t • x) ≤ ((-1 : Real) : EReal) := by
                have hmul :=
                  ereal_mul_le_mul_of_pos_left_general (t := t) (ht := ht) hle'
                have hright :
                    ((t : Real) : EReal) * ((-1 : Real) / t : EReal) = (-1 : EReal) := by
                  have hdiv : ((-1 : Real) / t : EReal) = (t⁻¹ : EReal) * (-1 : EReal) := by
                    simp [div_eq_mul_inv, mul_comm]
                  calc
                    (t : EReal) * ((-1 : Real) / t : EReal) =
                        (t : EReal) * ((t⁻¹ : EReal) * (-1 : EReal)) := by
                          rw [hdiv]
                    _ = (-1 : EReal) := by
                          simpa using
                            (ereal_mul_inv_smul (t := t) (ht := ht) (x := (-1 : EReal)))
                have hmul' :
                    ((t : Real) : EReal) * rightScalarMultiple f s x ≤
                      ((-1 : Real) : EReal) := by
                  calc
                    ((t : Real) : EReal) * rightScalarMultiple f s x ≤
                        ((t : Real) : EReal) * ((-1 : Real) / t : EReal) := hmul
                    _ = (-1 : EReal) := hright
                have hspos' : 0 < t * s := mul_pos ht hspos
                have hpos_ts :=
                  rightScalarMultiple_pos (f := f) (lam := t * s) hfconv hspos' (t • x)
                have hpos_s :=
                  rightScalarMultiple_pos (f := f) (lam := s) hfconv hspos x
                have hsmul : (t * s)⁻¹ • (t • x) = s⁻¹ • x := by
                  have ht0 : t ≠ 0 := ne_of_gt ht
                  have hs0 : s ≠ 0 := ne_of_gt hspos
                  have hscale : (t * s)⁻¹ * t = s⁻¹ := by
                    field_simp [ht0, hs0]
                  calc
                    (t * s)⁻¹ • (t • x) = ((t * s)⁻¹ * t) • x := by
                      rw [smul_smul]
                    _ = s⁻¹ • x := by
                      rw [hscale]
                have hsmul' : (s⁻¹ * t⁻¹) • t • x = s⁻¹ • x := by
                  have ht0 : t ≠ 0 := ne_of_gt ht
                  calc
                    (s⁻¹ * t⁻¹) • t • x = ((s⁻¹ * t⁻¹) * t) • x := by
                      rw [smul_smul]
                    _ = s⁻¹ • x := by
                      simp [ht0]
                have hmul1 :
                    ((t * s : Real) : EReal) * f (s⁻¹ • x) ≤ ((-1 : Real) : EReal) := by
                  have hmul1' :
                      ((t : EReal) * ((s : EReal) * f (s⁻¹ • x))) ≤ ((-1 : Real) : EReal) := by
                    simpa [hpos_s, mul_assoc] using hmul'
                  simpa [mul_comm, mul_left_comm, mul_assoc, EReal.coe_mul] using hmul1'
                have hmul2 :
                    ((t * s : Real) : EReal) * f ((t * s)⁻¹ • (t • x)) ≤ ((-1 : Real) : EReal) := by
                  simpa [hsmul'] using hmul1
                rw [hpos_ts]
                exact hmul2
              have hmem' :
                  (t • x, (-1 : Real)) ∈
                    epigraph (Set.univ : Set (Fin n → Real))
                      (rightScalarMultiple f (t * s)) :=
                (mem_epigraph_univ_iff (f := rightScalarMultiple f (t * s))).2 hle''
              refine Or.inl ?_
              refine Set.mem_iUnion.2 ⟨t * s, ?_⟩
              refine Set.mem_iUnion.2 ⟨mul_pos ht hspos, ?_⟩
              exact hmem'
            · have hrec' :
                (x, (-1 : Real) / t) ∈
                  Set.recessionCone
                    (epigraph (Set.univ : Set (Fin n → Real)) f) := by
                simpa [hrec] using hmem_vert
              have hrec'' :
                  (t • x, (-1 : Real)) ∈
                    Set.recessionCone
                      (epigraph (Set.univ : Set (Fin n → Real)) f) := by
                intro y hy s hs
                have hrec_mem := hrec' (x := y) hy (t := s * t) (by nlinarith)
                have ht0 : t ≠ 0 := ne_of_gt ht
                have hmul : s * (t * (-1 / t)) = -s := by
                  field_simp [ht0, mul_comm, mul_left_comm, mul_assoc]
                simpa [smul_smul, mul_assoc, hmul] using hrec_mem
              have hmem' :
                  (t • x, (-1 : Real)) ∈
                    epigraph (Set.univ : Set (Fin n → Real)) f0_plus := by
                simpa [hrec] using hrec''
              exact Or.inr hmem'
          have hmem_limit :
              ((0 : Fin n → Real), (-1 : Real)) ∈
                (⋃ (t : Real) (_ : 0 < t),
                  epigraph (Set.univ : Set (Fin n → Real)) (rightScalarMultiple f t)) ∪
                epigraph (Set.univ : Set (Fin n → Real)) f0_plus := by
            have hmem_seq :
                ∀ m : ℕ,
                  (((1 : Real) / (m + 1)) • x, (-1 : Real)) ∈
                    (⋃ (t : Real) (_ : 0 < t),
                      epigraph (Set.univ : Set (Fin n → Real)) (rightScalarMultiple f t)) ∪
                    epigraph (Set.univ : Set (Fin n → Real)) f0_plus := by
              intro m
              have hpos : 0 < (1 : Real) / (m + 1) := by
                have : 0 < (m + 1 : Real) := by
                  exact_mod_cast (Nat.succ_pos m)
                exact one_div_pos.mpr this
              simpa using (hmem_scaled ((1 : Real) / (m + 1)) hpos)
            have hlim :
                Filter.Tendsto
                  (fun n : ℕ => (((1 : Real) / (n + 1)) • x, (-1 : Real))) Filter.atTop
                    (𝓝 ((0 : Fin n → Real), (-1 : Real))) := by
              have h1 :
                  Filter.Tendsto
                    (fun n : ℕ => (1 : Real) / (n + 1)) Filter.atTop (𝓝 (0 : Real)) :=
                (tendsto_one_div_add_atTop_nhds_zero_nat :
                  Filter.Tendsto (fun n : ℕ => (1 : Real) / (n + 1)) Filter.atTop (𝓝 (0 : Real)))
              have h1' :
                  Filter.Tendsto (fun n : ℕ => ((1 : Real) / (n + 1)) • x) Filter.atTop
                    (𝓝 (0 : Fin n → Real)) := by
                have h1' :=
                  h1.smul
                    (tendsto_const_nhds :
                      Filter.Tendsto (fun _ : ℕ => x) Filter.atTop (𝓝 x))
                have hzero : (0 : Real) • x = (0 : Fin n → Real) := by
                  simp
                simpa [hzero] using h1'
              have h2 :
                  Filter.Tendsto (fun _ : ℕ => (-1 : Real)) Filter.atTop (𝓝 (-1 : Real)) :=
                tendsto_const_nhds
              exact Filter.Tendsto.prodMk_nhds h1' h2
            exact hclosed_union.mem_of_tendsto hlim (eventually_of_forall hmem_seq)
          -- show the union has no negative verticals
          have hneg_not :
              ((0 : Fin n → Real), (-1 : Real)) ∉
                (⋃ (t : Real) (_ : 0 < t),
                  epigraph (Set.univ : Set (Fin n → Real)) (rightScalarMultiple f t)) ∪
                epigraph (Set.univ : Set (Fin n → Real)) f0_plus := by
            intro hmem
            rcases hmem with hmem | hmem
            · rcases (Set.mem_iUnion).1 hmem with ⟨t, hmem⟩
              rcases (Set.mem_iUnion).1 hmem with ⟨ht, hmem⟩
              have hle :
                  rightScalarMultiple f t (0 : Fin n → Real) ≤ ((-1 : Real) : EReal) :=
                (mem_epigraph_univ_iff (f := rightScalarMultiple f t)).1 hmem
              have hpos0 : (0 : EReal) < rightScalarMultiple f t (0 : Fin n → Real) := by
                have hpos' : (0 : EReal) < (t : EReal) := by
                  simpa using (EReal.coe_lt_coe_iff).2 ht
                have hpos0' : (0 : EReal) < f (0 : Fin n → Real) := hf0
                have hright :=
                  rightScalarMultiple_pos (f := f) (lam := t) hfconv ht (0 : Fin n → Real)
                have hmul : (0 : EReal) < (t : EReal) * f (0 : Fin n → Real) :=
                  EReal.mul_pos hpos' hpos0'
                have hmul' : (0 : EReal) < rightScalarMultiple f t (0 : Fin n → Real) := by
                  rw [hright]
                  have hzero : (t⁻¹ : Real) • (0 : Fin n → Real) = 0 := by simp
                  rw [hzero]
                  exact hmul
                exact hmul'
              have hnot : ¬ (rightScalarMultiple f t (0 : Fin n → Real) ≤ ((-1 : Real) : EReal)) := by
                have hlt :
                    ((-1 : Real) : EReal) < rightScalarMultiple f t (0 : Fin n → Real) :=
                  lt_trans (by simp) hpos0
                exact not_le_of_gt hlt
              exact hnot hle
            · have hmem' :
                  (0, (-1 : Real)) ∈
                    Set.recessionCone
                      (epigraph (Set.univ : Set (Fin n → Real)) f) := by
                simpa [hrec] using hmem
              exact
                (no_neg_vertical_recession_epigraph (f := f) hfproper (μ := (-1 : Real))
                  (by norm_num)) hmem'
          exact (hneg_not hmem_limit).elim
        exact hproper
      -- closed epigraph identification
      have hclosure_epigraph :
          closure (epigraph (Set.univ : Set (Fin n → Real)) k) =
            closure (convexConeGeneratedEpigraph f) := by
          apply subset_antisymm
          · have hsubset :
              epigraph (Set.univ : Set (Fin n → Real)) k ⊆
                closure (convexConeGeneratedEpigraph f) := h_epi_subset
            have hsubset' :
                closure (epigraph (Set.univ : Set (Fin n → Real)) k) ⊆
                  closure (closure (convexConeGeneratedEpigraph f)) :=
              closure_mono hsubset
            simpa [closure_closure] using hsubset'
          · have hsubset :
              convexConeGeneratedEpigraph f ⊆
                epigraph (Set.univ : Set (Fin n → Real)) k := hcone_subset
            exact closure_mono hsubset
      have h_epi :=
        (epigraph_convexFunctionClosure_eq_closure_epigraph (f := k) hnotbot).1
      have hEq :
          epigraph (Set.univ : Set (Fin n → Real)) (convexFunctionClosure k) =
            closure (convexConeGeneratedEpigraph f) := by
        simpa [hclosure_epigraph] using h_epi
      have hle :
          convexFunctionClosure k x ≤
            sInf
              (Set.insert (f0_plus x)
                { z : EReal | ∃ lam : Real, 0 < lam ∧ z = rightScalarMultiple f lam x }) := by
        refine le_sInf ?_
        intro z hz
        rcases hz with rfl | hz
        · by_cases htop : f0_plus x = (⊤ : EReal)
          · simp [htop]
          · have hle0 : f0_plus x ≤ ((f0_plus x).toReal : EReal) :=
              EReal.le_coe_toReal htop
            have hmem0 :
                (x, (f0_plus x).toReal) ∈
                  epigraph (Set.univ : Set (Fin n → Real)) f0_plus :=
              (mem_epigraph_univ_iff (f := f0_plus)).2 hle0
            have hmem0' :
                (x, (f0_plus x).toReal) ∈
                    (⋃ (t : Real) (_ : 0 < t),
                      epigraph (Set.univ : Set (Fin n → Real)) (rightScalarMultiple f t)) ∪
                    epigraph (Set.univ : Set (Fin n → Real)) f0_plus := Or.inr hmem0
            have hmem_closure' :
                (x, (f0_plus x).toReal) ∈ closure (convexConeGeneratedEpigraph f) := by
              simpa [hclosure_union''] using hmem0'
            have hmem_closure :
                (x, (f0_plus x).toReal) ∈
                  epigraph (Set.univ : Set (Fin n → Real)) (convexFunctionClosure k) := by
              simpa [hEq] using hmem_closure'
            have hle' :
                convexFunctionClosure k x ≤ ((f0_plus x).toReal : EReal) :=
              (mem_epigraph_univ_iff (f := convexFunctionClosure k)).1 hmem_closure
            by_cases hbot : f0_plus x = (⊥ : EReal)
            · have hforall : ∀ μ : ℝ, convexFunctionClosure k x ≤ (μ : EReal) := by
                intro μ
                have hmemμ :
                    (x, μ) ∈ epigraph (Set.univ : Set (Fin n → Real)) f0_plus := by
                  have hleμ : f0_plus x ≤ (μ : EReal) := by
                    simp [hbot]
                  exact (mem_epigraph_univ_iff (f := f0_plus)).2 hleμ
                have hmemμ' :
                    (x, μ) ∈
                      (⋃ (t : Real) (_ : 0 < t),
                        epigraph (Set.univ : Set (Fin n → Real)) (rightScalarMultiple f t)) ∪
                      epigraph (Set.univ : Set (Fin n → Real)) f0_plus := Or.inr hmemμ
                have hmemμ'' :
                    (x, μ) ∈ closure (convexConeGeneratedEpigraph f) := by
                  simpa [hclosure_union''] using hmemμ'
                have hmemμ''' :
                    (x, μ) ∈
                      epigraph (Set.univ : Set (Fin n → Real)) (convexFunctionClosure k) := by
                  simpa [hEq] using hmemμ''
                exact (mem_epigraph_univ_iff (f := convexFunctionClosure k)).1 hmemμ'''
              have hbotc : convexFunctionClosure k x = (⊥ : EReal) := by
                apply (EReal.eq_bot_iff_forall_lt _).2
                intro y
                have hleμ : convexFunctionClosure k x ≤ ((y - 1 : ℝ) : EReal) :=
                  hforall (y - 1)
                have hlt : (y - 1 : ℝ) < y := by linarith
                have hlt' : ((y - 1 : ℝ) : EReal) < (y : EReal) :=
                  (EReal.coe_lt_coe_iff).2 hlt
                exact lt_of_le_of_lt hleμ hlt'
              simp [hbotc, hbot]
            · have hle'' : ((f0_plus x).toReal : EReal) ≤ f0_plus x :=
                EReal.coe_toReal_le hbot
              exact le_trans hle' hle''
        · rcases hz with ⟨lam, hlam, rfl⟩
          by_cases htop : rightScalarMultiple f lam x = (⊤ : EReal)
          · simp [htop]
          · have hle0 :
                rightScalarMultiple f lam x ≤
                  ((rightScalarMultiple f lam x).toReal : EReal) :=
              EReal.le_coe_toReal htop
            have hmem :
                (x, (rightScalarMultiple f lam x).toReal) ∈
                  epigraph (Set.univ : Set (Fin n → Real))
                    (rightScalarMultiple f lam) :=
              (mem_epigraph_univ_iff (f := rightScalarMultiple f lam)).2 hle0
            have hmem' :
                (x, (rightScalarMultiple f lam x).toReal) ∈
                  (⋃ (t : Real) (_ : 0 < t),
                    epigraph (Set.univ : Set (Fin n → Real)) (rightScalarMultiple f t)) ∪
                  epigraph (Set.univ : Set (Fin n → Real)) f0_plus := by
              refine Or.inl ?_
              refine Set.mem_iUnion.2 ⟨lam, ?_⟩
              refine Set.mem_iUnion.2 ⟨hlam, ?_⟩
              exact hmem
            have hmem_closure' :
                (x, (rightScalarMultiple f lam x).toReal) ∈
                  closure (convexConeGeneratedEpigraph f) := by
              simpa [hclosure_union''] using hmem'
            have hmem_epi' :
                (x, (rightScalarMultiple f lam x).toReal) ∈
                  epigraph (Set.univ : Set (Fin n → Real)) (convexFunctionClosure k) := by
              simpa [hEq] using hmem_closure'
            have hle' :
                convexFunctionClosure k x ≤
                  ((rightScalarMultiple f lam x).toReal : EReal) :=
              (mem_epigraph_univ_iff (f := convexFunctionClosure k)).1 hmem_epi'
            have hne_bot : rightScalarMultiple f lam x ≠ (⊥ : EReal) := by
              have hpos :=
                rightScalarMultiple_pos (f := f) (lam := lam) hfconv hlam x
              have hbot : f (lam⁻¹ • x) ≠ (⊥ : EReal) := hfproper.2.2 _ (by simp)
              simpa [hpos] using (ereal_mul_ne_bot_of_pos hlam hbot)
            have hle'' :
                ((rightScalarMultiple f lam x).toReal : EReal) ≤ rightScalarMultiple f lam x :=
              EReal.coe_toReal_le hne_bot
            exact le_trans hle' hle''
      have hge :
          sInf
              (Set.insert (f0_plus x)
                { z : EReal | ∃ lam : Real, 0 < lam ∧ z = rightScalarMultiple f lam x })
            ≤ convexFunctionClosure k x := by
        by_cases htop : convexFunctionClosure k x = (⊤ : EReal)
        · simp [htop]
        · have hset :
              (x, (convexFunctionClosure k x).toReal) ∈
                epigraph (Set.univ : Set (Fin n → Real)) (convexFunctionClosure k) := by
            have hle0 :
                convexFunctionClosure k x ≤ ((convexFunctionClosure k x).toReal : EReal) :=
              EReal.le_coe_toReal htop
            exact (mem_epigraph_univ_iff (f := convexFunctionClosure k)).2 hle0
          have hmem_union :
              (x, (convexFunctionClosure k x).toReal) ∈
                  (⋃ (t : Real) (_ : 0 < t),
                    epigraph (Set.univ : Set (Fin n → Real)) (rightScalarMultiple f t)) ∪
                  epigraph (Set.univ : Set (Fin n → Real)) f0_plus := by
            have hmem' :
                (x, (convexFunctionClosure k x).toReal) ∈
                  closure (convexConeGeneratedEpigraph f) := by
              simpa [hEq] using hset
            simpa [hclosure_union''] using hmem'
          have hproper_cl :
              ProperConvexFunctionOn (Set.univ : Set (Fin n → Real)) (convexFunctionClosure k) :=
            (convexFunctionClosure_closed_properConvexFunctionOn_and_agrees_on_ri (f := k)
              hkproper).1.2
          rcases hmem_union with hmem_union | hmem_union
          · rcases (Set.mem_iUnion).1 hmem_union with ⟨lam, hmem_union⟩
            rcases (Set.mem_iUnion).1 hmem_union with ⟨hlam, hmem_union⟩
            have hle' :
                rightScalarMultiple f lam x ≤ ((convexFunctionClosure k x).toReal : EReal) :=
              (mem_epigraph_univ_iff (f := rightScalarMultiple f lam)).1 hmem_union
            have hne_bot : convexFunctionClosure k x ≠ (⊥ : EReal) :=
              hproper_cl.2.2 x (by simp)
            have hle_to :
                ((convexFunctionClosure k x).toReal : EReal) ≤ convexFunctionClosure k x :=
              EReal.coe_toReal_le hne_bot
            have hle'' :
                rightScalarMultiple f lam x ≤ convexFunctionClosure k x := le_trans hle' hle_to
            have hmem :
                rightScalarMultiple f lam x ∈
                  Set.insert (f0_plus x)
                    { z : EReal | ∃ lam : Real, 0 < lam ∧ z = rightScalarMultiple f lam x } :=
              by
                right
                exact ⟨lam, hlam, rfl⟩
            have hle''' :
                sInf
                    (Set.insert (f0_plus x)
                      { z : EReal | ∃ lam : Real, 0 < lam ∧
                          z = rightScalarMultiple f lam x }) ≤
                  rightScalarMultiple f lam x := sInf_le hmem
            exact le_trans hle''' hle''
          · have hle' : f0_plus x ≤ ((convexFunctionClosure k x).toReal : EReal) :=
              (mem_epigraph_univ_iff (f := f0_plus)).1 hmem_union
            have hne_bot : convexFunctionClosure k x ≠ (⊥ : EReal) :=
              hproper_cl.2.2 x (by simp)
            have hle_to :
                ((convexFunctionClosure k x).toReal : EReal) ≤ convexFunctionClosure k x :=
              EReal.coe_toReal_le hne_bot
            have hle'' : f0_plus x ≤ convexFunctionClosure k x := le_trans hle' hle_to
            have hmem :
                f0_plus x ∈
                  Set.insert (f0_plus x)
                    { z : EReal | ∃ lam : Real, 0 < lam ∧ z = rightScalarMultiple f lam x } :=
              by
                left
                rfl
            have hle''' :
                sInf
                    (Set.insert (f0_plus x)
                      { z : EReal | ∃ lam : Real, 0 < lam ∧
                          z = rightScalarMultiple f lam x }) ≤
                  f0_plus x := sInf_le hmem
            exact le_trans hle''' hle''
      exact le_antisymm hle hge
    refine And.intro hcl_formula ?_
    · refine And.intro ?_ ?_
      · -- TODO: extract attainment from the closed epigraph description.
        intro x
        by_cases htop : convexFunctionClosure k x = (⊤ : EReal)
        ·
          have hmem :
              f0_plus x ∈
                Set.insert (f0_plus x)
                  { z : EReal | ∃ lam : Real, 0 < lam ∧ z = rightScalarMultiple f lam x } :=
            by
              apply (Set.mem_insert_iff).2
              left
              rfl
          have hle : convexFunctionClosure k x ≤ f0_plus x := by
            have hclx := hcl_formula x
            have hle := sInf_le hmem
            rw [hclx]
            exact hle
          have hf0 : f0_plus x = (⊤ : EReal) := by
            have : (⊤ : EReal) ≤ f0_plus x := by
              simpa [htop] using hle
            exact (top_le_iff.mp this)
          refine ⟨f0_plus x, ?_, ?_⟩
          · exact (Set.mem_insert_iff).2 (Or.inl rfl)
          · simp [htop, hf0]
        ·
          -- use the union membership for `(x, convexFunctionClosure k x)` to pick an attained value
          have hnotbot : ∀ x : Fin n → Real, k x ≠ (⊥ : EReal) := by
            intro x
            by_contra hbot
            have hle : k x ≤ ((-1 : Real) : EReal) := by
              simp [hbot]
            have hmem_epi :
                (x, (-1 : Real)) ∈ epigraph (Set.univ : Set (Fin n → Real)) k :=
              (mem_epigraph_univ_iff (f := k)).2 hle
            have hmem_closure : (x, (-1 : Real)) ∈ closure (convexConeGeneratedEpigraph f) :=
              h_epi_subset hmem_epi
            have hmem_union :
                (x, (-1 : Real)) ∈
                    (⋃ (t : Real) (_ : 0 < t),
                      epigraph (Set.univ : Set (Fin n → Real)) (rightScalarMultiple f t)) ∪
                    epigraph (Set.univ : Set (Fin n → Real)) f0_plus := by
              simpa [hclosure_union''] using hmem_closure
            -- but the union cannot contain any negative verticals
            have hneg_not :
                ((0 : Fin n → Real), (-1 : Real)) ∉
                  (⋃ (t : Real) (_ : 0 < t),
                    epigraph (Set.univ : Set (Fin n → Real)) (rightScalarMultiple f t)) ∪
                  epigraph (Set.univ : Set (Fin n → Real)) f0_plus := by
              intro hmem
              rcases hmem with hmem | hmem
              · rcases (Set.mem_iUnion).1 hmem with ⟨t, hmem⟩
                rcases (Set.mem_iUnion).1 hmem with ⟨ht, hmem⟩
                have hle' :
                    rightScalarMultiple f t (0 : Fin n → Real) ≤ ((-1 : Real) : EReal) :=
                  (mem_epigraph_univ_iff (f := rightScalarMultiple f t)).1 hmem
                have hpos0 : (0 : EReal) < rightScalarMultiple f t (0 : Fin n → Real) := by
                  have hpos' : (0 : EReal) < (t : EReal) := by
                    simpa using (EReal.coe_lt_coe_iff).2 ht
                  have hpos0' : (0 : EReal) < f (0 : Fin n → Real) := hf0
                  have hright :=
                    rightScalarMultiple_pos (f := f) (lam := t) hfconv ht (0 : Fin n → Real)
                  have hmul : (0 : EReal) < (t : EReal) * f (0 : Fin n → Real) :=
                    EReal.mul_pos hpos' hpos0'
                  have hmul' : (0 : EReal) < rightScalarMultiple f t (0 : Fin n → Real) := by
                    rw [hright]
                    have hzero : (t⁻¹ : Real) • (0 : Fin n → Real) = 0 := by simp
                    rw [hzero]
                    exact hmul
                  exact hmul'
                have hnot :
                    ¬ (rightScalarMultiple f t (0 : Fin n → Real) ≤ ((-1 : Real) : EReal)) := by
                  have hlt :
                      ((-1 : Real) : EReal) < rightScalarMultiple f t (0 : Fin n → Real) :=
                    lt_trans (by simp) hpos0
                  exact not_le_of_gt hlt
                exact hnot hle'
              · have hmem' :
                    (0, (-1 : Real)) ∈
                      Set.recessionCone
                        (epigraph (Set.univ : Set (Fin n → Real)) f) := by
                  simpa [hrec] using hmem
                exact
                  (no_neg_vertical_recession_epigraph (f := f) hfproper (μ := (-1 : Real))
                    (by norm_num)) hmem'
            -- use union equality to reach a contradiction
            have hmem0 :
                ((0 : Fin n → Real), (-1 : Real)) ∈
                  (⋃ (t : Real) (_ : 0 < t),
                    epigraph (Set.univ : Set (Fin n → Real)) (rightScalarMultiple f t)) ∪
                  epigraph (Set.univ : Set (Fin n → Real)) f0_plus := by
              -- from `hmem_union`, scale down to the origin and close
              have hclosed_union :
                  IsClosed
                    ((⋃ (t : Real) (_ : 0 < t),
                      epigraph (Set.univ : Set (Fin n → Real)) (rightScalarMultiple f t)) ∪
                      epigraph (Set.univ : Set (Fin n → Real)) f0_plus) := by
                simpa [hclosure_union''] using
                  (isClosed_closure (s := convexConeGeneratedEpigraph f))
              have hmem_seq :
                  ∀ m : ℕ,
                    (((1 : Real) / (m + 1)) • x, (-1 : Real)) ∈
                      (⋃ (t : Real) (_ : 0 < t),
                        epigraph (Set.univ : Set (Fin n → Real)) (rightScalarMultiple f t)) ∪
                      epigraph (Set.univ : Set (Fin n → Real)) f0_plus := by
                intro m
                have hpos : 0 < (1 : Real) / (m + 1) := by
                  have : 0 < (m + 1 : Real) := by
                    exact_mod_cast (Nat.succ_pos m)
                  exact one_div_pos.mpr this
                -- vertical line at `x` for `k x = ⊥`
                have hle' : k x ≤ ((-1 : Real) / ((1 : Real) / (m + 1)) : Real) := by
                  simp [hbot]
                have hmem_epi :
                    (x, (-1 : Real) / ((1 : Real) / (m + 1))) ∈
                      epigraph (Set.univ : Set (Fin n → Real)) k :=
                  (mem_epigraph_univ_iff (f := k)).2 hle'
                have hmem_closure' := h_epi_subset hmem_epi
                have hmem_union' :
                    (x, (-1 : Real) / ((1 : Real) / (m + 1))) ∈
                      (⋃ (t : Real) (_ : 0 < t),
                        epigraph (Set.univ : Set (Fin n → Real)) (rightScalarMultiple f t)) ∪
                      epigraph (Set.univ : Set (Fin n → Real)) f0_plus := by
                  simpa [hclosure_union''] using hmem_closure'
                -- scale within the cone
                rcases hmem_union' with hmem_union' | hmem_union'
                · rcases (Set.mem_iUnion).1 hmem_union' with ⟨s, hmem_union'⟩
                  rcases (Set.mem_iUnion).1 hmem_union' with ⟨hspos, hmem_union'⟩
                  have hle'' :
                      rightScalarMultiple f s x ≤
                        ((-1 : Real) / ((1 : Real) / (m + 1)) : EReal) :=
                    (mem_epigraph_univ_iff (f := rightScalarMultiple f s)).1 hmem_union'
                  have hle''' :
                      rightScalarMultiple f ((1 : Real) / (m + 1) * s)
                        (((1 : Real) / (m + 1)) • x) ≤ ((-1 : Real) : EReal) := by
                    have hpos' : 0 < (1 : Real) / (m + 1) := by
                      have : 0 < (m + 1 : Real) := by
                        exact_mod_cast (Nat.succ_pos m)
                      exact one_div_pos.mpr this
                    have hmul :=
                      ereal_mul_le_mul_of_pos_left_general (t := (1 : Real) / (m + 1))
                        (ht := hpos') hle''
                    have hright :
                        ((1 : Real) / (m + 1) : EReal) *
                            ((-1 : Real) / ((1 : Real) / (m + 1)) : EReal) =
                          (-1 : EReal) := by
                      have hdiv :
                          ((-1 : Real) / ((1 : Real) / (m + 1)) : EReal) =
                            (((1 : Real) / (m + 1))⁻¹ : EReal) * (-1 : EReal) := by
                        simp [div_eq_mul_inv, mul_comm]
                      calc
                        ((1 : Real) / (m + 1) : EReal) *
                            ((-1 : Real) / ((1 : Real) / (m + 1)) : EReal) =
                            ((1 : Real) / (m + 1) : EReal) *
                              (((1 : Real) / (m + 1))⁻¹ : EReal) * (-1 : EReal) := by
                                rw [hdiv, mul_assoc]
                        _ = (-1 : EReal) := by
                              simpa using
                                (ereal_mul_inv_smul (t := (1 : Real) / (m + 1)) (ht := hpos')
                                  (x := (-1 : EReal)))
                    have hmul' :
                        ((1 : Real) / (m + 1) : EReal) * rightScalarMultiple f s x ≤
                          ((-1 : Real) : EReal) := by
                      calc
                        ((1 : Real) / (m + 1) : EReal) * rightScalarMultiple f s x ≤
                            ((1 : Real) / (m + 1) : EReal) *
                              ((-1 : Real) / ((1 : Real) / (m + 1)) : EReal) := hmul
                        _ = (-1 : EReal) := hright
                    have hspos' : 0 < (1 : Real) / (m + 1) * s := mul_pos hpos' hspos
                    have hpos_ts :=
                      rightScalarMultiple_pos (f := f) (lam := (1 : Real) / (m + 1) * s)
                        hfconv hspos' (((1 : Real) / (m + 1)) • x)
                    have hpos_s :=
                      rightScalarMultiple_pos (f := f) (lam := s) hfconv hspos x
                    have hsmul :
                        ((1 : Real) / (m + 1) * s)⁻¹ • (((1 : Real) / (m + 1)) • x) = s⁻¹ • x := by
                      have ht0 : (1 : Real) / (m + 1) ≠ 0 := ne_of_gt hpos'
                      have hs0 : s ≠ 0 := ne_of_gt hspos
                      have hscale :
                          ((1 : Real) / (m + 1) * s)⁻¹ * ((1 : Real) / (m + 1)) = s⁻¹ := by
                        field_simp [ht0, hs0]
                      calc
                        ((1 : Real) / (m + 1) * s)⁻¹ • (((1 : Real) / (m + 1)) • x) =
                            (((1 : Real) / (m + 1) * s)⁻¹ * ((1 : Real) / (m + 1))) • x := by
                              rw [smul_smul]
                        _ = s⁻¹ • x := by
                              rw [hscale]
                    have hmul1 :
                        (((1 : Real) / (m + 1) * s : Real) : EReal) * f (s⁻¹ • x) ≤
                          ((-1 : Real) : EReal) := by
                      simpa [hpos_s, EReal.coe_mul, mul_assoc] using hmul'
                    have hsmul' :
                        (s⁻¹ * (m + 1 : Real)) • ((m + 1 : Real)⁻¹ • x) = s⁻¹ • x := by
                      have hne : (m + 1 : Real) ≠ 0 := by
                        exact_mod_cast (Nat.succ_ne_zero m)
                      calc
                        (s⁻¹ * (m + 1 : Real)) • ((m + 1 : Real)⁻¹ • x) =
                            ((s⁻¹ * (m + 1 : Real)) * (m + 1 : Real)⁻¹) • x := by
                              simp [smul_smul]
                        _ = s⁻¹ • x := by
                              simp [hne]
                    have hmul2 :
                        (((1 : Real) / (m + 1) * s : Real) : EReal) *
                            f (((1 : Real) / (m + 1) * s)⁻¹ • (((1 : Real) / (m + 1)) • x)) ≤
                          ((-1 : Real) : EReal) := by
                      simpa [div_eq_mul_inv, smul_smul, hsmul'] using hmul1
                    rw [hpos_ts]
                    exact hmul2
                  have hmem'' :
                      (((1 : Real) / (m + 1)) • x, (-1 : Real)) ∈
                        epigraph (Set.univ : Set (Fin n → Real))
                          (rightScalarMultiple f ((1 : Real) / (m + 1) * s)) :=
                    (mem_epigraph_univ_iff
                      (f := rightScalarMultiple f ((1 : Real) / (m + 1) * s))).2 hle'''
                  refine Or.inl ?_
                  refine Set.mem_iUnion.2 ⟨(1 : Real) / (m + 1) * s, ?_⟩
                  refine Set.mem_iUnion.2 ⟨mul_pos hpos hspos, hmem''⟩
                · have hmem'' :
                    (((1 : Real) / (m + 1)) • x, (-1 : Real)) ∈
                      epigraph (Set.univ : Set (Fin n → Real)) f0_plus := by
                    have hrec' :
                        (x, (-1 : Real) / ((1 : Real) / (m + 1))) ∈
                          Set.recessionCone
                            (epigraph (Set.univ : Set (Fin n → Real)) f) := by
                      simpa [hrec] using hmem_union'
                    have hrec'' :
                        (((1 : Real) / (m + 1)) • x, (-1 : Real)) ∈
                          Set.recessionCone
                            (epigraph (Set.univ : Set (Fin n → Real)) f) := by
                      intro y hy s hs
                      have hs0 : 0 ≤ s * (1 : Real) / (m + 1) := by
                        have hpos : 0 < (m + 1 : Real) := by
                          exact_mod_cast (Nat.succ_pos m)
                        have hpos' : 0 ≤ (1 : Real) / (m + 1) := by
                          exact le_of_lt (one_div_pos.mpr hpos)
                        have hs0' : 0 ≤ s * ((1 : Real) / (m + 1)) := mul_nonneg hs hpos'
                        simpa [div_eq_mul_inv, mul_assoc] using hs0'
                      have hrec_mem :=
                        hrec' (x := y) hy (t := s * (1 : Real) / (m + 1)) hs0
                      have hne : (m + 1 : Real) ≠ 0 := by
                        exact_mod_cast (Nat.succ_ne_zero m)
                      have hmul :
                          s * ((m + 1 : Real)⁻¹ * (-1 + -(m : Real))) = -s := by
                        field_simp [hne]
                        ring
                      simpa [div_eq_mul_inv, smul_smul, mul_comm, mul_left_comm, mul_assoc, hmul]
                        using hrec_mem
                    simpa [hrec] using hrec''
                  exact Or.inr hmem''
              have hlim :
                  Filter.Tendsto
                    (fun n : ℕ => (((1 : Real) / (n + 1)) • x, (-1 : Real))) Filter.atTop
                      (𝓝 ((0 : Fin n → Real), (-1 : Real))) := by
                have h1 :
                    Filter.Tendsto
                      (fun n : ℕ => (1 : Real) / (n + 1)) Filter.atTop (𝓝 (0 : Real)) :=
                  tendsto_one_div_add_atTop_nhds_zero_nat
                have h1' :
                    Filter.Tendsto (fun n : ℕ => ((1 : Real) / (n + 1)) • x) Filter.atTop
                      (𝓝 (0 : Fin n → Real)) := by
                        have h1' :=
                          h1.smul
                            (tendsto_const_nhds :
                              Filter.Tendsto (fun _ : ℕ => x) Filter.atTop (𝓝 x))
                        have hzero : (0 : Real) • x = (0 : Fin n → Real) := by
                          simp
                        simpa [hzero] using h1'
                have h2 :
                    Filter.Tendsto (fun _ : ℕ => (-1 : Real)) Filter.atTop (𝓝 (-1 : Real)) :=
                  tendsto_const_nhds
                exact Filter.Tendsto.prodMk_nhds h1' h2
              exact hclosed_union.mem_of_tendsto hlim (eventually_of_forall hmem_seq)
            exact (hneg_not hmem0).elim
          -- use the union membership at the closure value to pick a witness
          have hnotbot' : ∀ x : Fin n → Real, k x ≠ (⊥ : EReal) := hnotbot
          have h_epi :=
            (epigraph_convexFunctionClosure_eq_closure_epigraph (f := k) hnotbot').1
          have hclosure_epigraph :
              closure (epigraph (Set.univ : Set (Fin n → Real)) k) =
                closure (convexConeGeneratedEpigraph f) := by
            apply subset_antisymm
            · have hsubset :
                epigraph (Set.univ : Set (Fin n → Real)) k ⊆
                  closure (convexConeGeneratedEpigraph f) := h_epi_subset
              have hsubset' :
                  closure (epigraph (Set.univ : Set (Fin n → Real)) k) ⊆
                    closure (closure (convexConeGeneratedEpigraph f)) :=
                closure_mono hsubset
              simpa [closure_closure] using hsubset'
            · have hsubset :
                convexConeGeneratedEpigraph f ⊆
                  epigraph (Set.univ : Set (Fin n → Real)) k := hcone_subset
              exact closure_mono hsubset
          have hEq :
              epigraph (Set.univ : Set (Fin n → Real)) (convexFunctionClosure k) =
                closure (convexConeGeneratedEpigraph f) := by
            simpa [hclosure_epigraph] using h_epi
          have hmem :
              (x, (convexFunctionClosure k x).toReal) ∈
                epigraph (Set.univ : Set (Fin n → Real)) (convexFunctionClosure k) := by
            have hle :
                convexFunctionClosure k x ≤ ((convexFunctionClosure k x).toReal : EReal) :=
              EReal.le_coe_toReal htop
            exact (mem_epigraph_univ_iff (f := convexFunctionClosure k)).2 hle
          have hmem_union :
              (x, (convexFunctionClosure k x).toReal) ∈
                  (⋃ (t : Real) (_ : 0 < t),
                    epigraph (Set.univ : Set (Fin n → Real)) (rightScalarMultiple f t)) ∪
                  epigraph (Set.univ : Set (Fin n → Real)) f0_plus := by
            have hmem' : (x, (convexFunctionClosure k x).toReal) ∈
                closure (convexConeGeneratedEpigraph f) := by
              simpa [hEq] using hmem
            simpa [hclosure_union''] using hmem'
          have hproper_cl :
              ProperConvexFunctionOn (Set.univ : Set (Fin n → Real)) (convexFunctionClosure k) :=
            (convexFunctionClosure_closed_properConvexFunctionOn_and_agrees_on_ri (f := k)
              hkproper).1.2
          have hne_bot : convexFunctionClosure k x ≠ (⊥ : EReal) :=
            hproper_cl.2.2 x (by simp)
          have htoReal_le :
              ((convexFunctionClosure k x).toReal : EReal) ≤ convexFunctionClosure k x :=
            EReal.coe_toReal_le hne_bot
          rcases hmem_union with hmem_union | hmem_union
          · rcases (Set.mem_iUnion).1 hmem_union with ⟨lam, hmem_union⟩
            rcases (Set.mem_iUnion).1 hmem_union with ⟨hlam, hmem_union⟩
            have hle' :
                rightScalarMultiple f lam x ≤ ((convexFunctionClosure k x).toReal : EReal) :=
              (mem_epigraph_univ_iff (f := rightScalarMultiple f lam)).1 hmem_union
            have hle'' : rightScalarMultiple f lam x ≤ convexFunctionClosure k x :=
              le_trans hle' htoReal_le
            have hmem_set :
                rightScalarMultiple f lam x ∈
                  Set.insert (f0_plus x)
                    { z : EReal | ∃ lam : Real, 0 < lam ∧ z = rightScalarMultiple f lam x } := by
              apply (Set.mem_insert_iff).2
              right
              exact ⟨lam, hlam, rfl⟩
            have hle_sInf : convexFunctionClosure k x ≤ rightScalarMultiple f lam x := by
              have hclx := hcl_formula x
              have hle := sInf_le hmem_set
              rw [hclx]
              exact hle
            have hEq : convexFunctionClosure k x = rightScalarMultiple f lam x :=
              le_antisymm hle_sInf hle''
            exact ⟨rightScalarMultiple f lam x, hmem_set, hEq⟩
          · have hle' : f0_plus x ≤ ((convexFunctionClosure k x).toReal : EReal) :=
              (mem_epigraph_univ_iff (f := f0_plus)).1 hmem_union
            have hle'' : f0_plus x ≤ convexFunctionClosure k x :=
              le_trans hle' htoReal_le
            have hmem_set :
                f0_plus x ∈
                  Set.insert (f0_plus x)
                    { z : EReal | ∃ lam : Real, 0 < lam ∧ z = rightScalarMultiple f lam x } :=
              by
                apply (Set.mem_insert_iff).2
                left
                rfl
            have hle_sInf : convexFunctionClosure k x ≤ f0_plus x := by
              have hclx := hcl_formula x
              have hle := sInf_le hmem_set
              rw [hclx]
              exact hle
            have hEq : convexFunctionClosure k x = f0_plus x :=
              le_antisymm hle_sInf hle''
            exact ⟨f0_plus x, hmem_set, hEq⟩
      · intro hdom0
        have hk_pos_formula :=
          posHomGenerated_formula_pos (n := n) (f := f) hfconv hfinite hdom0
        have hk_pos_formula' :
            ∀ x : Fin n → Real,
              k x = sInf { z : EReal | ∃ lam : Real, 0 < lam ∧ z = rightScalarMultiple f lam x } := by
          rw [hk]
          exact hk_pos_formula
        refine And.intro ?_ ?_
        · -- TODO: show `k` is closed from the closure-cone identification.
          -- show `convexFunctionClosure k = k`
          have hnotbot : ∀ x : Fin n → Real, k x ≠ (⊥ : EReal) := by
            intro x
            by_contra hbot
            have hle : k x ≤ ((-1 : Real) : EReal) := by
              simp [hbot]
            have hmem_epi :
                (x, (-1 : Real)) ∈ epigraph (Set.univ : Set (Fin n → Real)) k :=
              (mem_epigraph_univ_iff (f := k)).2 hle
            have hmem_closure : (x, (-1 : Real)) ∈ closure (convexConeGeneratedEpigraph f) :=
              h_epi_subset hmem_epi
            have hmem_union :
                (x, (-1 : Real)) ∈
                    (⋃ (t : Real) (_ : 0 < t),
                      epigraph (Set.univ : Set (Fin n → Real)) (rightScalarMultiple f t)) ∪
                    epigraph (Set.univ : Set (Fin n → Real)) f0_plus := by
              simpa [hclosure_union''] using hmem_closure
            -- no negative verticals
            have hneg_not :
                ((0 : Fin n → Real), (-1 : Real)) ∉
                  (⋃ (t : Real) (_ : 0 < t),
                    epigraph (Set.univ : Set (Fin n → Real)) (rightScalarMultiple f t)) ∪
                  epigraph (Set.univ : Set (Fin n → Real)) f0_plus := by
              intro hmem
              rcases hmem with hmem | hmem
              · rcases (Set.mem_iUnion).1 hmem with ⟨t, hmem⟩
                rcases (Set.mem_iUnion).1 hmem with ⟨ht, hmem⟩
                have hle' :
                    rightScalarMultiple f t (0 : Fin n → Real) ≤ ((-1 : Real) : EReal) :=
                  (mem_epigraph_univ_iff (f := rightScalarMultiple f t)).1 hmem
                have hpos0 : (0 : EReal) < rightScalarMultiple f t (0 : Fin n → Real) := by
                  have hpos' : (0 : EReal) < (t : EReal) := by
                    simpa using (EReal.coe_lt_coe_iff).2 ht
                  have hpos0' : (0 : EReal) < f (0 : Fin n → Real) := hf0
                  have hright :=
                    rightScalarMultiple_pos (f := f) (lam := t) hfconv ht (0 : Fin n → Real)
                  have hmul : (0 : EReal) < (t : EReal) * f (0 : Fin n → Real) :=
                    EReal.mul_pos hpos' hpos0'
                  have hmul' : (0 : EReal) < rightScalarMultiple f t (0 : Fin n → Real) := by
                    rw [hright]
                    have hzero : (t⁻¹ : Real) • (0 : Fin n → Real) = 0 := by simp
                    rw [hzero]
                    exact hmul
                  exact hmul'
                have hnot :
                    ¬ (rightScalarMultiple f t (0 : Fin n → Real) ≤ ((-1 : Real) : EReal)) := by
                  have hlt :
                      ((-1 : Real) : EReal) < rightScalarMultiple f t (0 : Fin n → Real) :=
                    lt_trans (by simp) hpos0
                  exact not_le_of_gt hlt
                exact hnot hle'
              · have hmem' :
                    (0, (-1 : Real)) ∈
                      Set.recessionCone
                        (epigraph (Set.univ : Set (Fin n → Real)) f) := by
                  simpa [hrec] using hmem
                exact
                  (no_neg_vertical_recession_epigraph (f := f) hfproper (μ := (-1 : Real))
                    (by norm_num)) hmem'
            -- scale to the origin
            have hclosed_union :
                IsClosed
                  ((⋃ (t : Real) (_ : 0 < t),
                    epigraph (Set.univ : Set (Fin n → Real)) (rightScalarMultiple f t)) ∪
                    epigraph (Set.univ : Set (Fin n → Real)) f0_plus) := by
              simpa [hclosure_union''] using
                (isClosed_closure (s := convexConeGeneratedEpigraph f))
            have hmem_seq :
                ∀ m : ℕ,
                  (((1 : Real) / (m + 1)) • x, (-1 : Real)) ∈
                    (⋃ (t : Real) (_ : 0 < t),
                      epigraph (Set.univ : Set (Fin n → Real)) (rightScalarMultiple f t)) ∪
                    epigraph (Set.univ : Set (Fin n → Real)) f0_plus := by
              intro m
              have hpos : 0 < (1 : Real) / (m + 1) := by
                have : 0 < (m + 1 : Real) := by
                  exact_mod_cast (Nat.succ_pos m)
                exact one_div_pos.mpr this
              -- vertical line at `x` for `k x = ⊥`
              have hle' : k x ≤ ((-1 : Real) / ((1 : Real) / (m + 1)) : Real) := by
                simp [hbot]
              have hmem_epi :
                  (x, (-1 : Real) / ((1 : Real) / (m + 1))) ∈
                    epigraph (Set.univ : Set (Fin n → Real)) k :=
                (mem_epigraph_univ_iff (f := k)).2 hle'
              have hmem_closure' := h_epi_subset hmem_epi
              have hmem_union' :
                  (x, (-1 : Real) / ((1 : Real) / (m + 1))) ∈
                    (⋃ (t : Real) (_ : 0 < t),
                      epigraph (Set.univ : Set (Fin n → Real)) (rightScalarMultiple f t)) ∪
                    epigraph (Set.univ : Set (Fin n → Real)) f0_plus := by
                simpa [hclosure_union''] using hmem_closure'
              -- scale within the cone
              rcases hmem_union' with hmem_union' | hmem_union'
              · rcases (Set.mem_iUnion).1 hmem_union' with ⟨s, hmem_union'⟩
                rcases (Set.mem_iUnion).1 hmem_union' with ⟨hspos, hmem_union'⟩
                have hle'' :
                    rightScalarMultiple f s x ≤
                      ((-1 : Real) / ((1 : Real) / (m + 1)) : EReal) :=
                  (mem_epigraph_univ_iff (f := rightScalarMultiple f s)).1 hmem_union'
                have hle''' :
                    rightScalarMultiple f ((1 : Real) / (m + 1) * s)
                      (((1 : Real) / (m + 1)) • x) ≤ ((-1 : Real) : EReal) := by
                  have hpos' : 0 < (1 : Real) / (m + 1) := by
                    have : 0 < (m + 1 : Real) := by
                      exact_mod_cast (Nat.succ_pos m)
                    exact one_div_pos.mpr this
                  have hmul :=
                    ereal_mul_le_mul_of_pos_left_general (t := (1 : Real) / (m + 1))
                      (ht := hpos') hle''
                  have hne : (1 : Real) / (m + 1) ≠ 0 := ne_of_gt hpos'
                  have hmul' :
                      ((1 : Real) / (m + 1) : EReal) * rightScalarMultiple f s x ≤
                        ((-1 : Real) : EReal) := by
                    have hright :
                        ((1 : Real) / (m + 1) : EReal) *
                            ((-1 : Real) / ((1 : Real) / (m + 1)) : EReal) = (-1 : EReal) := by
                      have hdiv :
                          ((-1 : Real) / ((1 : Real) / (m + 1)) : EReal) =
                            (((1 : Real) / (m + 1))⁻¹ : EReal) * (-1 : EReal) := by
                        simp [div_eq_mul_inv, mul_comm]
                      calc
                        ((1 : Real) / (m + 1) : EReal) *
                            ((-1 : Real) / ((1 : Real) / (m + 1)) : EReal) =
                            ((1 : Real) / (m + 1) : EReal) *
                              (((1 : Real) / (m + 1))⁻¹ : EReal) * (-1 : EReal) := by
                                rw [hdiv, mul_assoc]
                        _ = (-1 : EReal) := by
                              simpa using
                                (ereal_mul_inv_smul (t := (1 : Real) / (m + 1)) (ht := hpos')
                                  (x := (-1 : EReal)))
                    calc
                      ((1 : Real) / (m + 1) : EReal) * rightScalarMultiple f s x ≤
                          ((1 : Real) / (m + 1) : EReal) *
                            ((-1 : Real) / ((1 : Real) / (m + 1)) : EReal) := hmul
                      _ = (-1 : EReal) := hright
                  have hspos' : 0 < (1 : Real) / (m + 1) * s := mul_pos hpos' hspos
                  have hpos1 :=
                    rightScalarMultiple_pos (f := f) (lam := (1 : Real) / (m + 1) * s)
                      hfconv hspos' (((1 : Real) / (m + 1)) • x)
                  have hpos2 :=
                    rightScalarMultiple_pos (f := f) (lam := s) hfconv hspos x
                  have hsmul :
                      ((1 : Real) / (m + 1) * s)⁻¹ • (((1 : Real) / (m + 1)) • x) = s⁻¹ • x := by
                    have ht0 : (1 : Real) / (m + 1) ≠ 0 := ne_of_gt hpos'
                    have hs0 : s ≠ 0 := ne_of_gt hspos
                    have hscale :
                        ((1 : Real) / (m + 1) * s)⁻¹ * ((1 : Real) / (m + 1)) = s⁻¹ := by
                      field_simp [ht0, hs0]
                    calc
                      ((1 : Real) / (m + 1) * s)⁻¹ • (((1 : Real) / (m + 1)) • x) =
                          (((1 : Real) / (m + 1) * s)⁻¹ * ((1 : Real) / (m + 1))) • x := by
                            rw [smul_smul]
                      _ = s⁻¹ • x := by
                            rw [hscale]
                  have hmul1 :
                      (((1 : Real) / (m + 1) * s : Real) : EReal) * f (s⁻¹ • x) ≤
                        ((-1 : Real) : EReal) := by
                    simpa [hpos2, EReal.coe_mul, mul_assoc] using hmul'
                  have hsmul' :
                      (s⁻¹ * (m + 1 : Real)) • ((m + 1 : Real)⁻¹ • x) = s⁻¹ • x := by
                    have hne : (m + 1 : Real) ≠ 0 := by
                      exact_mod_cast (Nat.succ_ne_zero m)
                    calc
                      (s⁻¹ * (m + 1 : Real)) • ((m + 1 : Real)⁻¹ • x) =
                          ((s⁻¹ * (m + 1 : Real)) * (m + 1 : Real)⁻¹) • x := by
                            simp [smul_smul]
                      _ = s⁻¹ • x := by
                            simp [hne]
                  have hmul2 :
                      (((1 : Real) / (m + 1) * s : Real) : EReal) *
                          f (((1 : Real) / (m + 1) * s)⁻¹ • (((1 : Real) / (m + 1)) • x)) ≤
                        ((-1 : Real) : EReal) := by
                    simpa [div_eq_mul_inv, smul_smul, hsmul'] using hmul1
                  rw [hpos1]
                  exact hmul2
                have hmem'' :
                    (((1 : Real) / (m + 1)) • x, (-1 : Real)) ∈
                      epigraph (Set.univ : Set (Fin n → Real))
                        (rightScalarMultiple f ((1 : Real) / (m + 1) * s)) :=
                  (mem_epigraph_univ_iff
                    (f := rightScalarMultiple f ((1 : Real) / (m + 1) * s))).2 hle'''
                refine Or.inl ?_
                refine Set.mem_iUnion.2 ⟨(1 : Real) / (m + 1) * s, ?_⟩
                refine Set.mem_iUnion.2 ⟨mul_pos hpos hspos, hmem''⟩
              · have hmem'' :
                  (((1 : Real) / (m + 1)) • x, (-1 : Real)) ∈
                    epigraph (Set.univ : Set (Fin n → Real)) f0_plus := by
                  have hrec' :
                      (x, (-1 : Real) / ((1 : Real) / (m + 1))) ∈
                        Set.recessionCone
                          (epigraph (Set.univ : Set (Fin n → Real)) f) := by
                    rw [hrec]
                    exact hmem_union'
                  have hrec'' :
                      (((1 : Real) / (m + 1)) • x, (-1 : Real)) ∈
                        Set.recessionCone
                          (epigraph (Set.univ : Set (Fin n → Real)) f) := by
                    intro y hy s hs
                    have hs0 : 0 ≤ s * (1 : Real) / (m + 1) := by
                      have hpos : 0 < (m + 1 : Real) := by
                        exact_mod_cast (Nat.succ_pos m)
                      have hpos' : 0 ≤ (1 : Real) / (m + 1) := by
                        exact le_of_lt (one_div_pos.mpr hpos)
                      have hs0' : 0 ≤ s * ((1 : Real) / (m + 1)) := mul_nonneg hs hpos'
                      simpa [div_eq_mul_inv, mul_assoc] using hs0'
                    have hrec_mem :=
                      hrec' (x := y) hy (t := s * (1 : Real) / (m + 1)) hs0
                    have hne : (m + 1 : Real) ≠ 0 := by
                      exact_mod_cast (Nat.succ_ne_zero m)
                    have hmul :
                        s * ((m + 1 : Real)⁻¹ * (-1 + -(m : Real))) = -s := by
                      field_simp [hne]
                      ring
                    simpa [div_eq_mul_inv, smul_smul, mul_assoc, hmul] using hrec_mem
                  rw [← hrec]
                  exact hrec''
                exact Or.inr hmem''
            have hlim :
                Filter.Tendsto
                  (fun n : ℕ => (((1 : Real) / (n + 1)) • x, (-1 : Real))) Filter.atTop
                    (𝓝 ((0 : Fin n → Real), (-1 : Real))) := by
              have h1 :
                  Filter.Tendsto
                    (fun n : ℕ => (1 : Real) / (n + 1)) Filter.atTop (𝓝 (0 : Real)) :=
                tendsto_one_div_add_atTop_nhds_zero_nat
              have h1' :
                  Filter.Tendsto (fun n : ℕ => ((1 : Real) / (n + 1)) • x) Filter.atTop
                    (𝓝 (0 : Fin n → Real)) := by
                      have h1' :=
                        h1.smul
                          (tendsto_const_nhds :
                            Filter.Tendsto (fun _ : ℕ => x) Filter.atTop (𝓝 x))
                      rw [← (zero_smul (M₀ := Real) (A := Fin n → Real) (m := x))]
                      exact h1'
              have h2 :
                  Filter.Tendsto (fun _ : ℕ => (-1 : Real)) Filter.atTop (𝓝 (-1 : Real)) :=
                tendsto_const_nhds
              exact Filter.Tendsto.prodMk_nhds h1' h2
            have hmem0 :=
              hclosed_union.mem_of_tendsto hlim (eventually_of_forall hmem_seq)
            exact (hneg_not hmem0).elim
        -- now compare the formulas to get closure equality
          have hle' :
              ∀ x : Fin n → Real,
                k x ≤ f0_plus x := by
            intro x
            -- `f0_plus x` is a recession direction: use the recession cone property
            have hdom0' : f (0 : Fin n → Real) ≠ (⊤ : EReal) :=
              mem_effectiveDomain_imp_ne_top (x := (0 : Fin n → Real)) hdom0
            have hbot0 : f (0 : Fin n → Real) ≠ (⊥ : EReal) := hfproper.2.2 _ (by simp)
            set r : Real := (f (0 : Fin n → Real)).toReal
            have h0mem :
                ((0 : Fin n → Real), r) ∈
                  epigraph (Set.univ : Set (Fin n → Real)) f := by
              have hle0 : f (0 : Fin n → Real) ≤ (r : EReal) :=
                EReal.le_coe_toReal hdom0'
              exact (mem_epigraph_univ_iff (f := f)).2 hle0
            have hleμ :
                ∀ μ : Real, f0_plus x ≤ (μ : EReal) → k x ≤ (μ : EReal) := by
              intro μ hμ
              have hrec_mem :
                  (x, μ) ∈ Set.recessionCone
                    (epigraph (Set.univ : Set (Fin n → Real)) f) := by
                have hmem' :
                    (x, μ) ∈ epigraph (Set.univ : Set (Fin n → Real)) f0_plus :=
                  (mem_epigraph_univ_iff (f := f0_plus)).2 hμ
                rw [hrec]
                exact hmem'
              have hbound :
                  ∀ t : Real, 0 ≤ t →
                    f (t • x) ≤ ((r + t * μ : Real) : EReal) := by
                intro t ht
                have hmem := hrec_mem (x := ((0 : Fin n → Real), r)) h0mem (t := t) ht
                have hmem' :
                    (t • x, r + t * μ) ∈ epigraph (Set.univ : Set (Fin n → Real)) f := by
                  simpa [add_comm, add_left_comm, add_assoc] using hmem
                exact (mem_epigraph_univ_iff (f := f)).1 hmem'
              have hle_rs :
                  ∀ lam : Real, 0 < lam →
                    rightScalarMultiple f lam x ≤ ((μ + lam * r : Real) : EReal) := by
                intro lam hlam
                have hbound' :
                    f (lam⁻¹ • x) ≤ ((r + lam⁻¹ * μ : Real) : EReal) := by
                  have hbound0 := hbound (lam⁻¹) (by
                    have : 0 < lam⁻¹ := inv_pos.mpr hlam
                    exact le_of_lt this)
                  simpa [smul_smul, inv_mul_cancel, hlam.ne'] using hbound0
                have hmul :=
                  ereal_mul_le_mul_of_pos_left_general (t := lam) (ht := hlam) hbound'
                have hne : (lam : Real) ≠ 0 := ne_of_gt hlam
                have hmul' :
                    rightScalarMultiple f lam x ≤ ((μ + lam * r : Real) : EReal) := by
                  have hpos :=
                    rightScalarMultiple_pos (f := f) (lam := lam) hfconv hlam x
                  -- rewrite using the positive formula
                  have hpos' :
                      rightScalarMultiple f lam x =
                        ((lam : Real) : EReal) * f (lam⁻¹ • x) := by
                    simpa using hpos
                  -- simplify the right side
                  have hright :
                      ((lam : Real) : EReal) *
                        ((r + lam⁻¹ * μ : Real) : EReal) =
                        ((μ + lam * r : Real) : EReal) := by
                    have hreal : lam * (r + lam⁻¹ * μ) = μ + lam * r := by
                      calc
                        lam * (r + lam⁻¹ * μ) = lam * r + lam * lam⁻¹ * μ := by ring
                        _ = lam * r + μ := by simp [hne]
                        _ = μ + lam * r := by ring
                    calc
                      ((lam : Real) : EReal) * ((r + lam⁻¹ * μ : Real) : EReal) =
                          ((lam * (r + lam⁻¹ * μ) : Real) : EReal) := by
                            simp [EReal.coe_mul]
                      _ = ((μ + lam * r : Real) : EReal) := by
                            simp [hreal]
                  calc
                    rightScalarMultiple f lam x =
                        ((lam : Real) : EReal) * f (lam⁻¹ • x) := by
                          exact hpos'
                    _ ≤ ((lam : Real) : EReal) * ((r + lam⁻¹ * μ : Real) : EReal) := hmul
                    _ = ((μ + lam * r : Real) : EReal) := hright
                exact hmul'
              have hle_k :
                  k x ≤ ((μ : Real) : EReal) := by
                have hform := hk_pos_formula' x
                -- k x is the infimum over positive scalings
                have hle' :
                    k x ≤ sInf { z : EReal | ∃ lam : Real, 0 < lam ∧
                      z = rightScalarMultiple f lam x } := by
                  exact le_of_eq hform
                have hle'' :
                    sInf { z : EReal | ∃ lam : Real, 0 < lam ∧
                      z = rightScalarMultiple f lam x } ≤ (μ : EReal) := by
                  refine (EReal.le_of_forall_lt_iff_le (x := (μ : EReal))
                    (y := sInf { z : EReal | ∃ lam : Real, 0 < lam ∧
                      z = rightScalarMultiple f lam x })).1 ?_
                  intro z hz
                  have hz' : μ < z := by
                    exact (EReal.coe_lt_coe_iff).1 hz
                  have hεpos : 0 < z - μ := by linarith
                  have hrpos : 0 < r := by
                    have hf0' : (0 : EReal) < f (0 : Fin n → Real) := hf0
                    simpa [r] using
                      (EReal.toReal_pos (x := f (0 : Fin n → Real)) hf0' hdom0')
                  have hpos : 0 < (z - μ) / r := by
                    exact div_pos hεpos hrpos
                  have hle_rs' :
                      rightScalarMultiple f ((z - μ) / r) x ≤ (z : EReal) := by
                    have hle' := hle_rs ((z - μ) / r) hpos
                    have hcalc : (μ + ((z - μ) / r) * r : Real) = z := by
                      have hrne : r ≠ 0 := ne_of_gt hrpos
                      calc
                        μ + ((z - μ) / r) * r = μ + (z - μ) := by
                          field_simp [hrne]
                        _ = z := by ring
                    simpa [hcalc] using hle'
                  have hmem :
                      rightScalarMultiple f ((z - μ) / r) x ∈
                        { z : EReal | ∃ lam : Real, 0 < lam ∧
                          z = rightScalarMultiple f lam x } := by
                    exact ⟨(z - μ) / r, hpos, rfl⟩
                  have hle'' := sInf_le hmem
                  exact le_trans hle'' hle_rs'
                exact le_trans hle' hle''
              exact hle_k
            have hle_all :
                k x ≤ sInf { μ : EReal | f0_plus x ≤ μ } := by
              refine le_sInf ?_
              intro μ hμ
              cases μ using EReal.rec with
              | bot =>
                  have hbot : f0_plus x = (⊥ : EReal) := (le_bot_iff.mp hμ)
                  have hforall : ∀ μ : ℝ, k x ≤ (μ : EReal) := by
                    intro μ
                    have hμ' : f0_plus x ≤ (μ : EReal) := by
                      simp [hbot]
                    exact hleμ μ hμ'
                  have hbotc : k x = (⊥ : EReal) := by
                    apply (EReal.eq_bot_iff_forall_lt _).2
                    intro y
                    have hleμ : k x ≤ ((y - 1 : ℝ) : EReal) := hforall (y - 1)
                    have hlt : (y - 1 : ℝ) < y := by linarith
                    have hlt' : ((y - 1 : ℝ) : EReal) < (y : EReal) :=
                      (EReal.coe_lt_coe_iff).2 hlt
                    exact lt_of_le_of_lt hleμ hlt'
                  simp [hbotc]
              | top =>
                  exact le_top
              | coe r =>
                  exact hleμ r hμ
            simpa [sInf_Ici_eq_self] using hle_all
          have hcl_eq : convexFunctionClosure k = k := by
            funext x
            -- use `sInf_insert` and the bound `k x ≤ f0_plus x`
            have hset :
                sInf
                  (Set.insert (f0_plus x)
                    { z : EReal | ∃ lam : Real, 0 < lam ∧
                        z = rightScalarMultiple f lam x }) =
                  sInf { z : EReal | ∃ lam : Real, 0 < lam ∧
                    z = rightScalarMultiple f lam x } := by
              have hle0 : sInf { z : EReal | ∃ lam : Real, 0 < lam ∧
                z = rightScalarMultiple f lam x } ≤ f0_plus x := by
                have hle0' : k x ≤ f0_plus x := hle' x
                have hkx := hk_pos_formula' x
                simpa [hkx] using hle0'
              have hS := sInf_insert (s := { z : EReal | ∃ lam : Real, 0 < lam ∧
                z = rightScalarMultiple f lam x }) (a := f0_plus x)
              -- `sInf_insert` gives `a ⊓ sInf S`; use `hle0` to rewrite
              have hmin : (f0_plus x) ⊓
                  sInf { z : EReal | ∃ lam : Real, 0 < lam ∧
                    z = rightScalarMultiple f lam x } =
                  sInf { z : EReal | ∃ lam : Real, 0 < lam ∧
                    z = rightScalarMultiple f lam x } := by
                exact inf_eq_right.mpr hle0
              have hS' :
                  sInf
                    (Set.insert (f0_plus x)
                      { z : EReal | ∃ lam : Real, 0 < lam ∧
                          z = rightScalarMultiple f lam x }) =
                    min (f0_plus x)
                      (sInf { z : EReal | ∃ lam : Real, 0 < lam ∧
                        z = rightScalarMultiple f lam x }) := by
                change
                  sInf
                    (insert (f0_plus x)
                      { z : EReal | ∃ lam : Real, 0 < lam ∧
                          z = rightScalarMultiple f lam x }) =
                    min (f0_plus x)
                      (sInf { z : EReal | ∃ lam : Real, 0 < lam ∧
                        z = rightScalarMultiple f lam x })
                exact hS
              calc
                sInf
                    (Set.insert (f0_plus x)
                      { z : EReal | ∃ lam : Real, 0 < lam ∧
                          z = rightScalarMultiple f lam x }) =
                    min (f0_plus x)
                      (sInf { z : EReal | ∃ lam : Real, 0 < lam ∧
                        z = rightScalarMultiple f lam x }) := hS'
                _ = sInf { z : EReal | ∃ lam : Real, 0 < lam ∧
                    z = rightScalarMultiple f lam x } := hmin
            -- now finish
            have hkx := hk_pos_formula' x
            -- use the derived formula for `convexFunctionClosure k`
            have hclx :
                convexFunctionClosure k x =
                  sInf
                    (Set.insert (f0_plus x)
                      { z : EReal | ∃ lam : Real, 0 < lam ∧
                          z = rightScalarMultiple f lam x }) := by
              exact hcl_formula x
            -- combine
            have hkx' :
                k x =
                  sInf { z : EReal | ∃ lam : Real, 0 < lam ∧
                    z = rightScalarMultiple f lam x } := by
              exact hkx
            calc
              convexFunctionClosure k x =
                  sInf
                    (Set.insert (f0_plus x)
                      { z : EReal | ∃ lam : Real, 0 < lam ∧
                          z = rightScalarMultiple f lam x }) := hclx
              _ = sInf { z : EReal | ∃ lam : Real, 0 < lam ∧
                    z = rightScalarMultiple f lam x } := hset
              _ = k x := hkx'.symm
          have hk_closed :
              ClosedConvexFunction k := by
            -- `convexFunctionClosure k` is lower semicontinuous, and equals `k`.
            have hls : LowerSemicontinuous (convexFunctionClosure k) := by
              -- lower semicontinuous hull is lower semicontinuous
              by_cases hbot' : ∀ x, k x ≠ (⊥ : EReal)
              · have hEq : convexFunctionClosure k = lowerSemicontinuousHull k := by
                  simp [convexFunctionClosure, hbot']
                have hls' : LowerSemicontinuous (lowerSemicontinuousHull k) := by
                  have hspec :=
                    Classical.choose_spec (exists_lowerSemicontinuousHull (n := n) k)
                  simpa using hspec.1
                simpa [hEq] using hls'
              ·
                simpa [convexFunctionClosure, hbot'] using
                  (lowerSemicontinuous_const :
                    LowerSemicontinuous (fun _ : Fin n → Real => (⊥ : EReal)))
            have hconv : ConvexFunction k := by
              simpa [ConvexFunction] using hk_conv
            have hls' : LowerSemicontinuous k := by
              simpa [hcl_eq] using hls
            exact ⟨hconv, hls'⟩
          exact hk_closed
        · simpa using hk_pos_formula'

end Section09
end Chap02
