-- This file is generated by scripts/gen_project_site.py.
-- Do not edit manually.

import VersoBlog
import ProjectSite.GeneratedPages

open Verso Genre Blog Site Syntax

namespace ProjectSite.RouteTable

def projectSite : Site := site ProjectSite.GeneratedPages.homePage /
  "book/" ProjectSite.GeneratedPages.homePage
  "chapters/chap00/section03/" ProjectSite.GeneratedPages.page_chap00_section03
  "chapters/chap00/section03_part1/" ProjectSite.GeneratedPages.page_chap00_section03_part1
  "chapters/chap00/section03_part2/" ProjectSite.GeneratedPages.page_chap00_section03_part2
  "chapters/chap00/section03_part3/" ProjectSite.GeneratedPages.page_chap00_section03_part3
  "chapters/chap00/section03_part4/" ProjectSite.GeneratedPages.page_chap00_section03_part4
  "chapters/chap00/section03_part5/" ProjectSite.GeneratedPages.page_chap00_section03_part5
  "chapters/chap01/section01/" ProjectSite.GeneratedPages.page_chap01_section01
  "chapters/chap01/section02/" ProjectSite.GeneratedPages.page_chap01_section02
  "chapters/chap01/section03/" ProjectSite.GeneratedPages.page_chap01_section03
  "chapters/chap01/section04/" ProjectSite.GeneratedPages.page_chap01_section04
  "chapters/chap01/section05/" ProjectSite.GeneratedPages.page_chap01_section05
  "chapters/chap02/section01/" ProjectSite.GeneratedPages.page_chap02_section01
  "chapters/chap02/section02/" ProjectSite.GeneratedPages.page_chap02_section02
  "chapters/chap02/section03/" ProjectSite.GeneratedPages.page_chap02_section03
  "chapters/chap02/section04/" ProjectSite.GeneratedPages.page_chap02_section04
  "chapters/chap02/section05/" ProjectSite.GeneratedPages.page_chap02_section05
  "chapters/chap02/section06/" ProjectSite.GeneratedPages.page_chap02_section06
  "chapters/chap03/section01/" ProjectSite.GeneratedPages.page_chap03_section01
  "chapters/chap03/section02/" ProjectSite.GeneratedPages.page_chap03_section02
  "chapters/chap03/section03/" ProjectSite.GeneratedPages.page_chap03_section03
  "chapters/chap03/section04/" ProjectSite.GeneratedPages.page_chap03_section04
  "chapters/chap03/section05/" ProjectSite.GeneratedPages.page_chap03_section05
  "chapters/chap03/section06/" ProjectSite.GeneratedPages.page_chap03_section06
  "chapters/chap04/section01/" ProjectSite.GeneratedPages.page_chap04_section01
  "chapters/chap04/section02/" ProjectSite.GeneratedPages.page_chap04_section02
  "chapters/chap04/section03/" ProjectSite.GeneratedPages.page_chap04_section03
  "chapters/chap04/section04/" ProjectSite.GeneratedPages.page_chap04_section04
  "chapters/chap05/section01/" ProjectSite.GeneratedPages.page_chap05_section01
  "chapters/chap05/section02/" ProjectSite.GeneratedPages.page_chap05_section02
  "chapters/chap05/section02_part1/" ProjectSite.GeneratedPages.page_chap05_section02_part1
  "chapters/chap05/section02_part2/" ProjectSite.GeneratedPages.page_chap05_section02_part2
  "chapters/chap05/section02_part3/" ProjectSite.GeneratedPages.page_chap05_section02_part3
  "chapters/chap05/section02_part4/" ProjectSite.GeneratedPages.page_chap05_section02_part4
  "chapters/chap05/section02_part5/" ProjectSite.GeneratedPages.page_chap05_section02_part5
  "chapters/chap05/section02_part6/" ProjectSite.GeneratedPages.page_chap05_section02_part6
  "chapters/chap05/section03/" ProjectSite.GeneratedPages.page_chap05_section03
  "chapters/chap05/section04/" ProjectSite.GeneratedPages.page_chap05_section04
  "chapters/chap05/section05/" ProjectSite.GeneratedPages.page_chap05_section05
  "chapters/chap06/section01/" ProjectSite.GeneratedPages.page_chap06_section01
  "chapters/chap06/section02/" ProjectSite.GeneratedPages.page_chap06_section02
  "chapters/chap06/section03/" ProjectSite.GeneratedPages.page_chap06_section03
  "chapters/chap07/section01/" ProjectSite.GeneratedPages.page_chap07_section01
  "chapters/chap07/section02/" ProjectSite.GeneratedPages.page_chap07_section02
  "chapters/chap07/section03/" ProjectSite.GeneratedPages.page_chap07_section03
  "chapters/chap07/section04/" ProjectSite.GeneratedPages.page_chap07_section04
  "chapters/chap07/section05/" ProjectSite.GeneratedPages.page_chap07_section05
  "chapters/chap07/section06/" ProjectSite.GeneratedPages.page_chap07_section06

end ProjectSite.RouteTable
