-- This file is generated by scripts/gen_project_site.py.
-- Do not edit manually.

import SiteSupport.LiterateModule

namespace ProjectSite.GeneratedPages

reasbook_page homePage from Papers.SmoothMinimization_Nesterov_2004.Paper as "SmoothMinimization_Nesterov_2004"
reasbook_page page_section01 from Papers.SmoothMinimization_Nesterov_2004.Sections.section01 as "section01" with ({showInNav := false} : Verso.Genre.Blog.Page.Meta)
reasbook_page page_section02 from Papers.SmoothMinimization_Nesterov_2004.Sections.section02 as "section02" with ({showInNav := false} : Verso.Genre.Blog.Page.Meta)
reasbook_page page_section02_part1 from Papers.SmoothMinimization_Nesterov_2004.Sections.section02_part1 as "section02_part1" with ({showInNav := false} : Verso.Genre.Blog.Page.Meta)
reasbook_page page_section02_part2 from Papers.SmoothMinimization_Nesterov_2004.Sections.section02_part2 as "section02_part2" with ({showInNav := false} : Verso.Genre.Blog.Page.Meta)
reasbook_page page_section02_part3 from Papers.SmoothMinimization_Nesterov_2004.Sections.section02_part3 as "section02_part3" with ({showInNav := false} : Verso.Genre.Blog.Page.Meta)
reasbook_page page_section03 from Papers.SmoothMinimization_Nesterov_2004.Sections.section03 as "section03" with ({showInNav := false} : Verso.Genre.Blog.Page.Meta)
reasbook_page page_section03_part1 from Papers.SmoothMinimization_Nesterov_2004.Sections.section03_part1 as "section03_part1" with ({showInNav := false} : Verso.Genre.Blog.Page.Meta)
reasbook_page page_section03_part2 from Papers.SmoothMinimization_Nesterov_2004.Sections.section03_part2 as "section03_part2" with ({showInNav := false} : Verso.Genre.Blog.Page.Meta)
reasbook_page page_section04 from Papers.SmoothMinimization_Nesterov_2004.Sections.section04 as "section04" with ({showInNav := false} : Verso.Genre.Blog.Page.Meta)
reasbook_page page_section04_part1 from Papers.SmoothMinimization_Nesterov_2004.Sections.section04_part1 as "section04_part1" with ({showInNav := false} : Verso.Genre.Blog.Page.Meta)
reasbook_page page_section04_part10 from Papers.SmoothMinimization_Nesterov_2004.Sections.section04_part10 as "section04_part10" with ({showInNav := false} : Verso.Genre.Blog.Page.Meta)
reasbook_page page_section04_part2 from Papers.SmoothMinimization_Nesterov_2004.Sections.section04_part2 as "section04_part2" with ({showInNav := false} : Verso.Genre.Blog.Page.Meta)
reasbook_page page_section04_part3 from Papers.SmoothMinimization_Nesterov_2004.Sections.section04_part3 as "section04_part3" with ({showInNav := false} : Verso.Genre.Blog.Page.Meta)
reasbook_page page_section04_part4 from Papers.SmoothMinimization_Nesterov_2004.Sections.section04_part4 as "section04_part4" with ({showInNav := false} : Verso.Genre.Blog.Page.Meta)
reasbook_page page_section04_part5 from Papers.SmoothMinimization_Nesterov_2004.Sections.section04_part5 as "section04_part5" with ({showInNav := false} : Verso.Genre.Blog.Page.Meta)
reasbook_page page_section04_part6 from Papers.SmoothMinimization_Nesterov_2004.Sections.section04_part6 as "section04_part6" with ({showInNav := false} : Verso.Genre.Blog.Page.Meta)
reasbook_page page_section04_part7 from Papers.SmoothMinimization_Nesterov_2004.Sections.section04_part7 as "section04_part7" with ({showInNav := false} : Verso.Genre.Blog.Page.Meta)
reasbook_page page_section04_part8 from Papers.SmoothMinimization_Nesterov_2004.Sections.section04_part8 as "section04_part8" with ({showInNav := false} : Verso.Genre.Blog.Page.Meta)
reasbook_page page_section04_part9 from Papers.SmoothMinimization_Nesterov_2004.Sections.section04_part9 as "section04_part9" with ({showInNav := false} : Verso.Genre.Blog.Page.Meta)
reasbook_page page_section05 from Papers.SmoothMinimization_Nesterov_2004.Sections.section05 as "section05" with ({showInNav := false} : Verso.Genre.Blog.Page.Meta)
reasbook_page page_section05_part1 from Papers.SmoothMinimization_Nesterov_2004.Sections.section05_part1 as "section05_part1" with ({showInNav := false} : Verso.Genre.Blog.Page.Meta)
reasbook_page page_section05_part2 from Papers.SmoothMinimization_Nesterov_2004.Sections.section05_part2 as "section05_part2" with ({showInNav := false} : Verso.Genre.Blog.Page.Meta)
reasbook_page page_section05_part3 from Papers.SmoothMinimization_Nesterov_2004.Sections.section05_part3 as "section05_part3" with ({showInNav := false} : Verso.Genre.Blog.Page.Meta)
reasbook_page page_section05_part4 from Papers.SmoothMinimization_Nesterov_2004.Sections.section05_part4 as "section05_part4" with ({showInNav := false} : Verso.Genre.Blog.Page.Meta)
reasbook_page page_section05_part5 from Papers.SmoothMinimization_Nesterov_2004.Sections.section05_part5 as "section05_part5" with ({showInNav := false} : Verso.Genre.Blog.Page.Meta)

end ProjectSite.GeneratedPages
