-- This file is generated by scripts/gen_project_site.py.
-- Do not edit manually.

import VersoBlog
import ProjectSite.GeneratedPages

open Verso Genre Blog Site Syntax

namespace ProjectSite.RouteTable

def projectSite : Site := site ProjectSite.GeneratedPages.homePage /
  "paper/" ProjectSite.GeneratedPages.homePage
  "sections/section01/" ProjectSite.GeneratedPages.page_section01
  "sections/section02/" ProjectSite.GeneratedPages.page_section02
  "sections/section02_part1/" ProjectSite.GeneratedPages.page_section02_part1
  "sections/section02_part2/" ProjectSite.GeneratedPages.page_section02_part2
  "sections/section02_part3/" ProjectSite.GeneratedPages.page_section02_part3
  "sections/section03/" ProjectSite.GeneratedPages.page_section03
  "sections/section03_part1/" ProjectSite.GeneratedPages.page_section03_part1
  "sections/section03_part2/" ProjectSite.GeneratedPages.page_section03_part2
  "sections/section04/" ProjectSite.GeneratedPages.page_section04
  "sections/section04_part1/" ProjectSite.GeneratedPages.page_section04_part1
  "sections/section04_part10/" ProjectSite.GeneratedPages.page_section04_part10
  "sections/section04_part2/" ProjectSite.GeneratedPages.page_section04_part2
  "sections/section04_part3/" ProjectSite.GeneratedPages.page_section04_part3
  "sections/section04_part4/" ProjectSite.GeneratedPages.page_section04_part4
  "sections/section04_part5/" ProjectSite.GeneratedPages.page_section04_part5
  "sections/section04_part6/" ProjectSite.GeneratedPages.page_section04_part6
  "sections/section04_part7/" ProjectSite.GeneratedPages.page_section04_part7
  "sections/section04_part8/" ProjectSite.GeneratedPages.page_section04_part8
  "sections/section04_part9/" ProjectSite.GeneratedPages.page_section04_part9
  "sections/section05/" ProjectSite.GeneratedPages.page_section05
  "sections/section05_part1/" ProjectSite.GeneratedPages.page_section05_part1
  "sections/section05_part2/" ProjectSite.GeneratedPages.page_section05_part2
  "sections/section05_part3/" ProjectSite.GeneratedPages.page_section05_part3
  "sections/section05_part4/" ProjectSite.GeneratedPages.page_section05_part4
  "sections/section05_part5/" ProjectSite.GeneratedPages.page_section05_part5

end ProjectSite.RouteTable
